### ISSUE TITLE
How to change 'localhost' so app can be accessed from outside/public IP?

### ISSUE THREAD

**Issue by randwa1k** [angular-fullstack/generator-angular-fullstack#107]
I have installed generator-angular-fullstack on my AWS EC2 machine with a public IP address without any major problems (just the [jpegtran minor issue](https://github.com/yeoman/node-jpegtran-bin/issues/17)). When I run `grunt serve`, it starts "Waiting ... " as expected, but none of my browsers could connect to the.public.ip:9000.

I've seen this before with just the plain generator-angular. It was [solved](http://stackoverflow.com/a/21896178/3290121) in Gruntfile.js by changing `localhost` to "`0.0.0.0` to access the server from outside".

I did try replacing all the "localhost"s to "0.0.0.0" in my current angular-fullstack's Gruntfile.js, but I still can't connect to it, nothing seems to change from the `grunt serve` output at least.  

**If the localhost is indeed the problem, how should I fix it?**
**If not, what is causing the failure to connect on browsers?**

Here is my `grunt serve` output:

```
Loading "imagemin.js" tasks...ERROR
>> Error: Cannot find module 'jpegtran-bin'

Running "serve" task

Running "clean:server" (clean) task
Cleaning .tmp...OK

Running "bower-install:app" (bower-install) task

Running "concurrent:server" (concurrent) task

    Loading "imagemin.js" tasks...ERROR
    >> Error: Cannot find module 'jpegtran-bin'

    Running "copy:styles" (copy) task
    Copied 1 files

    Done, without errors.


    Execution Time (2014-03-02 00:36:37 UTC)
    loading tasks   6ms  ▇▇▇▇▇▇▇▇▇▇▇ 21%
    copy:styles    21ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 75%
    Total 28ms

Running "autoprefixer:dist" (autoprefixer) task
Prefixed file ".tmp/styles/main.css" created.

Running "express:dev" (express) task
Starting background Express server
debugger listening on port 5858
Express server listening on port 9000 in development mode

Running "open:server" (open) task

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/home/ubuntu/fs_a/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (/home/ubuntu/fs_a/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/ubuntu/fs_a/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:478:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:415:13)

Running "watch" task
Waiting...
Reloading watch config...
Loading "imagemin.js" tasks...ERROR
>> Error: Cannot find module 'jpegtran-bin'

Running "watch" task
Waiting...OK
>> File "Gruntfile.js" changed.

Completed in 0.001s at Sun Mar 02 2014 00:37:16 GMT+0000 (UTC) - Waiting...

Reloading watch config...
Loading "imagemin.js" tasks...ERROR
>> Error: Cannot find module 'jpegtran-bin'

Running "watch" task
Waiting...
```

**Comment by Globik** [comment]
But why mongos.js can't connect to localhost: 27017 without internet connection? I am on windows7. Mongodb shell works just fine, also port 28017 is ok. But in browser there is error 500.
