### ISSUE TITLE
Problem to run two instances of angular-fullstack

### ISSUE THREAD

**Issue by ghost** [angular-fullstack/generator-angular-fullstack#1090]
I'm having a problem to run two instances of angular-fullstack at same machine, the first was the problem with the livereload port, but it was resolved after change the port, but there's another conflict with node-inspector, i think node-inspector isn't receiving the the parameters that was updated at Gruntfile.

```
For instance: 
    // Debugging with node inspector
    'node-inspector': {
      custom: {
        options: {
          'web-port': 1337,
          'web-host': 'localhost',
          'debug-port': 5857,
          'save-live-edit': true,
          'no-preload': true,
          'stack-trace-limit': 4,
          'hidden': ['node_modules']
        }
      }
    },

```
The port 5858 still conflicting, any idea ?

**Comment by kingcody** [comment]
Actually its because `grunt-express-server` is starting node with the debug port.

In `Gruntfile.js` the `express` config:
```diff
    express: {
      options: {
        port: process.env.PORT || 9000
      },
      dev: {
        options: {
          script: 'server/app.js',
-          debug: true
+          debug: 5859
        }
      },
      prod: {
        options: {
          script: 'dist/server/app.js'
        }
      }
    },
```

**Comment by eduardonunesptoptal** [comment]
Unfortunately change the debug port wasn't solve, also i had changed others parameters like:

```
@@ -35,12 +35,12 @@ module.exports = function (grunt) {
     },
     express: {
       options: {
-        port: process.env.PORT || 9000
+        port: process.env.PORT || 9001
       },
       dev: {
         options: {
           script: 'server/app.js',
-          debug: true
+          debug: 5859,
         }
       },
       prod: {
@@ -103,7 +103,7 @@ module.exports = function (grunt) {
           '<%= yeoman.client %>/assets/images/{,*//*}*.{png,jpg,jpeg,gif,webp,svg}'
         ],
         options: {
-          livereload: true
+          livereload: 35728
         }
       },
       express: {
@@ -112,7 +112,7 @@ module.exports = function (grunt) {
         ],
         tasks: ['express:dev', 'wait'],
         options: {
-          livereload: true,
+          livereload: 35728,
           nospawn: true //Without this option specified express won't be reloaded
         }
       }
@@ -188,7 +188,8 @@ module.exports = function (grunt) {
     'node-inspector': {
       custom: {
         options: {
-          'web-host': 'localhost'
+          'web-host': 'localhost',
+	        'debug-port': 5859
         }
       }
     },
@@ -200,7 +201,7 @@ module.exports = function (grunt) {
         options: {
           nodeArgs: ['--debug-brk'],
           env: {
-            PORT: process.env.PORT || 9000
+            PORT: process.env.PORT || 9001
           },
           callback: function (nodemon) {
             nodemon.on('log', function (event) {
@@ -210,7 +211,7 @@ module.exports = function (grunt) {
             // opens browser on initial server start
             nodemon.on('config:update', function () {
               setTimeout(function () {
-                require('open')('http://localhost:8080/debug?port=5858');
+                require('open')('http://localhost:8080/debug?port=5859');
               }, 500);
             });
           }
```

```
Running "express:dev" (express) task
Starting background Express server
Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:839:11)
    at exports._exceptionWithHostPort (util.js:862:20)
    at Agent.Server._listen2 (net.js:1215:14)
    at listen (net.js:1251:10)
    at Agent.Server.listen (net.js:1341:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:69:9)
    at node.js:948:3
```

**Comment by kingcody** [comment]
So you're still receiving that error?

**Comment by abutcher-gh** [comment]
It is actually the node instance running express that is trying to bind the default 5858 port.   Adding

    opts: ['--debug=5859']

to `express.dev.options` should fix it.  You'll likely still need your existing changes to reference the non-default `5859` port.

**Comment by jpagand** [comment]
@abutcher-gh works like a charm!

**Comment by ikb42** [comment]
Perhaps a cleaner place for all the port settings would be useful.

**Comment by Awk34** [comment]
@ikb42 probably in `server/config/local.env`

**Comment by molerat619** [comment]
@abutcher-gh where do you add that line?

**Comment by Awk34** [comment]
Closing in favor of #957
