### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by vsshaposhnikov** [angular-fullstack/generator-angular-fullstack#1473]
Hello! Could you help me, after executing the command "yo angular-fullstack"  i have this 
message -  
"SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\Владимир\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\babel-core\lib\api\register\node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Владимир\AppData\Roaming\npm\node_modules\generator-angular-fullstack\app\index.js:9:28)
    at Module._compile (module.js:435:26)
"
Please help me.

**Comment by mcpDESIGNS** [comment]
What versions of node / npm / bower / generator are you using?
Did you install the generator properly?

**Comment by Awk34** [comment]
Closed due to inactivity.
