### ISSUE TITLE
Testing fails on new endpoint

### ISSUE THREAD

**Issue by anotherweblog** [angular-fullstack/generator-angular-fullstack#1478]
Hi,

I created an endpoint with yo angular-fullstack:endpoint order

When running grunt I get the following errors:

```
  1) Order API: POST /api/orders should respond with the newly created order:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (server/api/order/order.integration.js:53:20)
      at Test.<anonymous> (server/api/order/order.integration.js:48:11)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  2) Order API: GET /api/orders/:id should respond with the requested order:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (server/api/order/order.integration.js:81:17)
      at Test.<anonymous> (server/api/order/order.integration.js:72:11)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)

  3) Order API: PUT /api/orders/:id should respond with the updated order:
     TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (server/api/order/order.integration.js:113:24)
      at Test.<anonymous> (server/api/order/order.integration.js:104:11)
      at Test.assert (node_modules/supertest/lib/test.js:156:6)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1521:8)
```

The test does not fail for the automatically created endpoint "things". My project is pretty much out of the box from angular-fullstack, I have only changed the Order Model scheme after creating it.

Running Node 4.2.3.

Any ideas?

EDIT:

Oh, I just answered my own question. The testing is, of course, not aware of my changed model scheme. Is there a way to automatically update the test or should I do that manually?

EDIT 2:

I updated the test manually and it compiles. Guess that's the only way? But if there's some way to create a new test that matches the updated model, please let me know. :-)

(I no longer have an issue, so I guess this thread can be closed)

**Comment by Awk34** [comment]
There's no easy way to automate that kind of thing
