### ISSUE TITLE
run-sequence error

### ISSUE THREAD

**Issue by Jbz797** [angular-fullstack/generator-angular-fullstack#1504]
Hi all!
After executing the command "gulp serve" i get this error:

    [11:04:07] Requiring external module babel-core/register
    [11:04:07] Using gulpfile ~/Dropbox/Node_Angular/***/gulpfile.babel.js
    [11:04:07] Starting 'serve'...
    [11:04:07] Starting 'clean:tmp'...
    [11:04:07] Starting 'constant'...
    [11:04:07] Finished 'constant' after 62 ms
    [11:04:07] Finished 'clean:tmp' after 73 ms
    [11:04:07] Starting 'lint:scripts'...
    [11:04:07] Starting 'lint:scripts:client'...
    [11:04:07] Starting 'lint:scripts:server'...
    [11:04:07] Starting 'inject'...
    [11:04:07] 'inject' errored after 80 μs
    [11:04:07] Error: Task inject:css is listed more than once. This is probably a typo.
    at /home/***/Dropbox/Node_Angular/***/node_modules/run-sequence/index.js:24:11
    at Array.forEach (native)
    at verifyTaskSets (/home/***/Dropbox/Node_Angular/***/node_modules/run-sequence/index.js:13:11)
    at /home/***/Dropbox/Node_Angular/***/node_modules/run-sequence/index.js:32:4
    at Array.forEach (native)
    at verifyTaskSets (/home/***/Dropbox/Node_Angular/***/node_modules/run-sequence/index.js:13:11)
    at runSequence (/home/***/Dropbox/Node_Angular/***/node_modules/run-sequence/index.js:94:2)
    at Gulp.<anonymous> (/home/***/Dropbox/Node_Angular/***/gulpfile.babel.js:148:5)
    at module.exports (/home/***/Dropbox/Node_Angular/***/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/***/Dropbox/Node_Angular/***/node_modules/orchestrator/index.js:273:3)
    [11:04:07] 'serve' errored after 142 ms
    [11:04:07] Error in plugin 'run-sequence'
    Message:
        An error occured in task 'inject'.
    [11:04:07] 'lint:scripts' errored after 69 ms
    [11:04:07] Error in plugin 'run-sequence'
    Message:
        An error occured in task 'serve'.
    [11:04:07] 'lint:scripts' errored after 69 ms
    [11:04:07] Error in plugin 'run-sequence'
    Message:
        An error occured in task 'inject'.

    client/app/app.constant.js
      line 2  col 3   Missing "use strict" statement.
      line 2  col 46  Strings must use singlequote.
      line 4  col 22  Strings must use singlequote.
      line 5  col 16  Strings must use singlequote.
      line 6  col 16  Strings must use singlequote.
      line 7  col 15  Strings must use singlequote.
      line 8  col 16  Strings must use singlequote.

      ✖  1 error
      ⚠  6 warnings

    [11:04:08] Finished 'lint:scripts:client' after 506 ms
    [11:04:08] Finished 'lint:scripts:server' after 501 ms

Could you help me?
Thanks,

**Comment by Awk34** [comment]
I'm pretty sure I know what's going on here. You must have selected plain CSS instead of a transpiler. Take a look at this code: https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.1.1/app/templates/gulpfile.babel(gulp).js#L176-L207

There's one Gulp task called `inject:css` that injects a link tag for each CSS file into your index.html. Then there's `inject:<%= styleExt %>`, which once scaffolding is done would be another `inject:css` in your case, but could be `inject:scss`, `inject:less`, or `inject:styl` for the transpiler options. This task is supposed to insert `@import foo.scss`, etc files into the main `app.scss`, etc file. In the case of just using vanilla CSS, though, you won't need this second task. It will also collide with the first task.

**Comment by Jbz797** [comment]
Thank you very much its works!

I also delete the third 'inject' in line 160: https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.1.1/app/templates/gulpfile.babel%28gulp%29.js#L160
