### ISSUE TITLE
Object [object Object] has no method 'isAbsolute'

### ISSUE THREAD

**Issue by asirko** [angular-fullstack/generator-angular-fullstack#1513]
I tried the command `yo angular-fullstack test --gulp` and I recieved that message :

```
Out of the box I create an AngularJS app with an Express server.

# Client

? What would you like to write markup with? HTML
? What would you like to write stylesheets with? Less
? What Angular router would you like to use? uiRouter
? Would you like to include Bootstrap? Yes
? Would you like to include UI Bootstrap? Yes

# Server

? What would you like to use for data modeling? Mongoose (MongoDB)
? Would you scaffold out an authentication boilerplate? Yes
? Would you like to include additional oAuth strategies? 
? Would you like to use socket.io? Yes

# Project

? What would you like to write tests with? Mocha + Chai + Sinon
? What would you like to write Chai assertions with? Expect
You're using the fantastic NgComponent generator.

Initializing yo-rc.json configuration.


events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object [object Object] has no method 'isAbsolute'
    at Generator.processDirectory (/usr/local/lib/node_modules/generator-angular-fullstack/util.js:110:19)
    at Generator.generateProject (/usr/local/lib/node_modules/generator-angular-fullstack/app/generator.js:409:14)
    at /usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

System ubuntu : 14.04
NodeJS : v0.10.25
NPM : 1.3.10
YO : 1.5.0
Grunt-Cli : v0.1.13 (but useless since I want to try the gulp setup)
Gulp (Cli) : 3.9.0
git : 1.9.1
mongo (shell and db) : 2.4.9

Any ideas ?

**Comment by chinnichaitanya** [comment]
I think that is because of NodeJS version. Please upgrade and try again.

**Comment by Awk34** [comment]
We suggest Node 4.2.3+, but you should at **least** upgrade to 0.12.9. Old versions of Node don't have that `isAbsolute` function.

**Comment by asirko** [comment]
Indeed, it worked directly ! thank you so much !

**Comment by javidrashid** [comment]
upgrading to node fixed this problem for me. Thank You.
