### ISSUE TITLE
Error: Cannot find module 'mkdirp' after running yo angular-fullstack:route xyz

### ISSUE THREAD

**Issue by molerat619** [angular-fullstack/generator-angular-fullstack#1529]
After running `yo angular-fullstack:route xyz` I get following error.

     module.js:339
         throw err;
         ^

     Error: Cannot find module 'mkdirp'
         at Function.Module._resolveFilename (module.js:337:15)
         at Function.Module._load (module.js:287:25)
         at Module.require (module.js:366:17)
         at require (module.js:385:17)
         at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:8:14)
         at Module._compile (module.js:425:26)
         at Object.Module._extensions..js (module.js:432:10)
         at Module.load (module.js:356:32)
         at Function.Module._load (module.js:311:12)
        at Module.require (module.js:366:17)

I am working with a MacBook and I have the whole project folder's rights set to 777. npm@3.3.6 and node@5.0.0. Does anybody know how I can fix this?

**Comment by molerat619** [comment]
Nothing, nobody?

**Comment by Awk34** [comment]
Try re-installing Yeoman

**Comment by molerat619** [comment]
that worked
