### ISSUE TITLE
Unexpected token "import"

### ISSUE THREAD

**Issue by motan** [angular-fullstack/generator-angular-fullstack#1568]
When I try to run 
```
yo angular-fullstack:endpoint myurl
```
in Terminal window in WebStorm, an error occurs. Unexpected token "import" in generator.js in generator-angular-fullstack. 
Node version 5.4.1, npm version 3.3.12, OS Windows 10

**Comment by ericmontreal** [comment]
Same error for me:
$ sudo yo angular-fullstack myapp
/usr/local/lib/node_modules/generator-angular-fullstack/app/generator.js:3
import fs from 'fs';
^^^^^^

SyntaxError: **Unexpected token import**
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/usr/local/lib/node_modules/babel-core/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-core/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js:9:28)
    at Module._compile (module.js:413:34)

Node v.5.6.0,  npm v.3.6.0, babel-core:5.8.35, generator-angular-fullstack v 3.3.0 ( so index.js files already fixed)

Any clue ?

**Comment by malikperang** [comment]
How did you solved this?
