### ISSUE TITLE
Babel Error when I run Gulp

### ISSUE THREAD

**Issue by anauleau** [angular-fullstack/generator-angular-fullstack#1622]
I'm getting a babel error when i try to run gulp tasks. I've uninstalled and reinstalled all the deps but keep getting this problem.

```
-SFO1-SFO1296:ngFullstack anauleau$ gulp serve
[10:29:35] Requiring external module babel-register
/Users/anauleau/sandbox/ngFullstack/gulpfile.babel.js:4
import _ from 'lodash';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at loader (/Users/anauleau/sandbox/ngFullstack/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/anauleau/sandbox/ngFullstack/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
M-SFO1-SFO1296:ngFullstack anauleau$
```

I'm running the following versions:
node 4.2.6
gulp 3.9.1
npm 3.6.0

**Comment by Awk34** [comment]
I'm assuming you upgraded to Babel 6. See https://github.com/gulpjs/gulp/issues/1364 .
