### ISSUE TITLE
File 'client/components/modal/modal.service.ts' not found.

### ISSUE THREAD

**Issue by bitflower** [angular-fullstack/generator-angular-fullstack#1647]
Fresh setup with latest generator just downloaded now.

Setup:
- Gulp
- Typescript
- Node 4.x
- OSX 10.10.5

Init went fine except that I had to post install kerberos & tslint.

When firing up with gulp serve I get this:
[21:22:19] Starting 'transpile:client'...
error TS6053: File 'client/components/modal/modal.service.ts' not found.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: error TS6053: File 'client/components/modal/modal.service.ts' not found.
    at DestroyableTransform.<anonymous> (/Volumes/Daten/Projekte/bitflower/DoodleMonsta/Codebase/MEAN2/App/node_modules/gulp-typescript/release/project.js:69:33)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at finishMaybe (/Volumes/Daten/Projekte/bitflower/DoodleMonsta/Codebase/MEAN2/App/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:511:14)
    at endWritable (/Volumes/Daten/Projekte/bitflower/DoodleMonsta/Codebase/MEAN2/App/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:521:3)
    at DestroyableTransform.Writable.end (/Volumes/Daten/Projekte/bitflower/DoodleMonsta/Codebase/MEAN2/App/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:486:5)
    at DestroyableTransform.onend (/Volumes/Daten/Projekte/bitflower/DoodleMonsta/Codebase/MEAN2/App/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:545:10)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at DestroyableTransform.emit (events.js:166:7)
    at endReadableNT (/Volumes/Daten/Projekte/bitflower/DoodleMonsta/Codebase/MEAN2/App/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:960:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
Segmentation fault: 11

Indeed the file is not there. I have not checked "UI Bootstrap". Might that be the case?

**Comment by Awk34** [comment]
That indeed is the case.

**Comment by Awk34** [comment]
To fix this, just remove the modal service from your `tsconfig.client.json`

**Comment by bitflower** [comment]
I did so, thanks man
