### ISSUE TITLE
gulpfile.babel.js , why not javascript?

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#1671]
I was surprised, like others, to see the the javascript option has been removed, and now it's only babel or typescript.
i have selected the babel option, and now i have this file: gulpfile.babel.js
but gulp is refusing to process this file, because, well, it's not the standard gulp.
so i suppose i have to convert it somehow to js, but how?
any tip would be appreciated. i'm working with sublime if it matters.
thanks!

**Comment by Awk34** [comment]
Gulp uses https://github.com/js-cli/js-interpret , and the generated project will include babel-core, so using the gulpfile should work out of the box.

**Comment by RonAlmog** [comment]
thanks. it did not work. here is what i see in the console:

D:\Projects\MEAN\fullts>gulp serve
[22:05:07] Failed to load external module babel/register
D:\Projects\MEAN\fullts\gulpfile.babel.js:4
import _ from 'lodash';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (C:\Users\Ron\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\Ron\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\Users\Ron\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)


any idea where to go next?

**Comment by neelavar** [comment]
I'm also facing issues - owing to sudden disappearance of Vanilla JS support in Rel. 3.x.
What is the motivation behind - removing Vanilla JS from the radar?

**Comment by Awk34** [comment]
@neelavar see https://github.com/angular-fullstack/generator-angular-fullstack/issues/1281
