### ISSUE TITLE
Gulp:build-client error (File not found with singular glob)

### ISSUE THREAD

**Issue by dariospadoni** [angular-fullstack/generator-angular-fullstack#1678]
When I try to run gulp:build-client task I get an error (File not found with singular glob), see error stack below...any hint?

```
/Users/dario/Projects/amavido/gulpfile.babel.js build:client
Requiring external module babel-core/register
Using gulpfile ~/Projects/amavido/gulpfile.babel.js
Starting 'transpile:client'...
Starting 'styles'...
Starting 'html'...
Starting 'constant'...
Finished 'constant' after 87 ms
Finished 'styles' after 1.87 s
Finished 'html' after 1.88 s
Finished 'transpile:client' after 2.49 s
Starting 'build:client'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error: File not found with singular glob: /Users/dario/Projects/amavido/.tmp/amavido/app/app.js
    at DestroyableTransform.<anonymous> (/Users/dario/Projects/amavido/node_modules/gulp-useref/lib/streamManager.js:90:36)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at emitOne (events.js:82:20)
    at Through2.emit (events.js:169:7)
    at OrderedStreams.<anonymous> (/Users/dario/Projects/amavido/node_modules/gulp-useref/node_modules/glob-stream/index.js:138:20)
    at emitOne (events.js:77:13)
    at OrderedStreams.emit (events.js:169:7)
    at emitOne (events.js:77:13)
    at DestroyableTransform.emit (events.js:169:7)
    at Glob.<anonymous> (/Users/dario/Projects/amavido/node_modules/gulp-useref/node_modules/glob-stream/index.js:38:16)
    at Glob.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (/Users/dario/Projects/amavido/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/Users/dario/Projects/amavido/node_modules/gulp-useref/node_modules/glob-stream/node_modules/glob/glob.js:159:12)

```

**Comment by dariospadoni** [comment]
I've found a workaround for the issue.
Basically gulp-useref searches for files in the wrong folder (_.tmp/projectName/app/**_) which does not exist. My work around consisted in transform its search path by using transformPath option in my gulp file from

```
plugins.useref()

```
to

```
plugins.useref({
            transformPath: function(filePath) {
              return filePath.replace('projectName/app','app')
            }
            }))
```
