### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by Fahrradflucht** [angular-fullstack/generator-angular-fullstack#1721]
I get this warnings all over the place in my application and in a newly generated test-app:
```
Warning: a promise was created in a handler but was not returned from it
    at Query.exec (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/mongoose/lib/query.js:2131:10)
    at me (/Users/User/Code/Javascript/angular-fullstack-example/server/api/user/user.controller.js:108:59)
    at Layer.handle [as handle_request] (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/express/lib/router/route.js:131:13)
    at next (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/composable-middleware/lib/composable-middleware.js:40:9)
    at /Users/User/Code/Javascript/angular-fullstack-example/server/auth/auth.service.js:36:11
From previous event:
    at Middleware_Common_Object.<anonymous> (/Users/User/Code/Javascript/angular-fullstack-example/server/auth/auth.service.js:31:10)
    at next (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/composable-middleware/lib/composable-middleware.js:59:18)
    at /Users/User/Code/Javascript/angular-fullstack-example/node_modules/express-jwt/lib/index.js:122:7
    at /Users/User/Code/Javascript/angular-fullstack-example/node_modules/express-jwt/lib/index.js:114:13
    at DEFAULT_REVOKED_FUNCTION (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/express-jwt/lib/index.js:7:61)
    at checkRevoked (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/express-jwt/lib/index.js:107:9)
    at fn (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/Users/User/Code/Javascript/angular-fullstack-example/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
It isn't limited to the `/me` route. If I parse the stack trace correctly it's most likely something in `auth.service.js` but I didn't change anything in there.

**Comment by Awk34** [comment]
This is because we upgraded Bluebird to version 3. It throws a warning if you create a promise, but don't return it.

**Comment by jillmolloy** [comment]
There's an unreturned promise in server/auth/auth.service.js as the warning mentions.

I got this warning to disappear by adding a return on line 36. Not sure if this is the right way to go about it, but everything seems to be working fine.

```javascript
export function isAuthenticated() {
  return compose()
    // Validate jwt
    .use(function(req, res, next) {
      // allow access_token to be passed through query parameter as well
      if (req.query && req.query.hasOwnProperty('access_token')) {
        req.headers.authorization = 'Bearer ' + req.query.access_token;
      }
      validateJwt(req, res, next);
    })
    // Attach user to request
    .use(function(req, res, next) {
      User.findById(req.user._id).exec()
        .then(user => {
          if (!user) {
            return res.status(401).end();
          }
          req.user = user;
          next();
          return null;
        })
        .catch(err => next(err));
    });
}
```

**Comment by danillobarbosa** [comment]
@jillmolloy 
Works for me! Thanks!!!

**Comment by NinjaEde** [comment]
@jillmolloy: isn't it better to return the user instead of null?

such like:
`       .then(user => {
          if (!user) {
            return res.status(401).end();
          }
          req.user = user;
          next();
          return user;`

That worked for me also.

**Comment by jillmolloy** [comment]
@NinjaEde – I'm not sure the return is actually being used anywhere so it's really just the fact that there's _something_ being returned that suppresses the warning – but yeah, that seems like a good approach

**Comment by molerat619** [comment]
So what's the right solution to this now? 

```
LocationMatrix.findAll({})
    .then(function(result){
      var results = {...};
      
      return res.status(200).json(results);
    })
    .catch(handleError(res));
```

I get this here too.
