### ISSUE TITLE
Error: Cannot find module 'mout'

### ISSUE THREAD

**Issue by 123wowow123** [angular-fullstack/generator-angular-fullstack#1726]
installation failing with the following msg:

`npm WARN EPEERINVALID mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
module.js:327
    throw err;
    ^

Error: Cannot find module 'mout'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:7:12)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
`

**Comment by Awk34** [comment]
Try reinstalling
