### ISSUE TITLE
Error: Cannot find module 'jshint/src/cli' on fresh install.

### ISSUE THREAD

**Issue by collinmesser** [angular-fullstack/generator-angular-fullstack#1731]
A clean install throws this error when I try to run "Gulp Serve". It appears to me that jshint is installed though and I have it installed globally.

```

collinmesser at Collins-MacBook-Air in ~/code/apps/jsapps/mean/test2
$ gulp serve
[14:02:08] Requiring external module babel-register
module.js:340
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/collinmesser/Code/Apps/jsapps/MEAN/test2/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/collinmesser/Code/Apps/jsapps/MEAN/test2/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/collinmesser/Code/Apps/jsapps/MEAN/test2/node_modules/gulp-jshint/src/index.js:2:15)
    at Module._compile (module.js:425:26)
    at Module._extensions..js (module.js:432:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/collinmesser/Code/Apps/jsapps/MEAN/test2/node_modules/babel-register/lib/node.js:134:7)

```

**Comment by dynamicmonkeys** [comment]
Are you sure the jshint bin is installed though or just gulp-jshint?

What does:
`jshint --version`
give you?

I had a clean c9 container, installed but came across the same problem:
`npm install -g --save-dev jshint`
fixed it for me

`jshint --version`
jshint v2.9.1

**Comment by collinmesser** [comment]
If I run:
`
jshint --version 
`
I get jshint v2.9.1 both globally and in the project repo. 

What worked for me was downgrading the local jshint to version 2.8.0 following the advice here [https://github.com/spalger/gulp-jshint/issues/131](https://github.com/spalger/gulp-jshint/issues/131). 
`
npm install --save-dev jshint@2.8.0
`

Apparently jshint is a peer dependency of gulp-jshint and for some reason the most recent version doesn't seem to register correctly.

**Comment by aendrew** [comment]
This still occurs as of 12 April 2016. I resolved it locally by reinstalling gulp-jshint and jshint:

Seems like `package.json` might need an update...

`npm install --save-dev jshint gulp-jshint`

**Comment by panique** [comment]
+1, same here
