### ISSUE TITLE
grunt serve, not working

### ISSUE THREAD

**Issue by FructuosoRobles** [angular-fullstack/generator-angular-fullstack#1734]
I got this error.

`Starting background Express server
Debugger listening on port 5858
/Users/BalioTech/Desktop/aaa/node_modules/babel-core/lib/transformation/file/options/option-manager.js:179
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-class-properties" specified in "/Users/BalioTech/Desktop/.babelrc" at 0, attempted to resolve relative to "/Users/BalioTech/Desktop"
    at /Users/BalioTech/Desktop/aaa/node_modules/babel-core/lib/transformation/file/options/option-manager.js:179:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/BalioTech/Desktop/aaa/node_modules/babel-core/lib/transformation/file/options/option-manager.js:155:20)
    at OptionManager.mergeOptions (/Users/BalioTech/Desktop/aaa/node_modules/babel-core/lib/transformation/file/options/option-manager.js:277:36)
    at OptionManager.addConfig (/Users/BalioTech/Desktop/aaa/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/Users/BalioTech/Desktop/aaa/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/Users/BalioTech/Desktop/aaa/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at compile (/Users/BalioTech/Desktop/aaa/node_modules/babel-register/lib/node.js:81:45)
    at loader (/Users/BalioTech/Desktop/aaa/node_modules/babel-register/lib/node.js:126:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/BalioTech/Desktop/aaa/node_modules/babel-register/lib/node.js:136:7)
Stopping Express server

Running "wait" task
>> Waiting for server reload...
Done waiting!

Running "open:server" (open) task

Running "watch" task
Waiting...

`

**Comment by Awk34** [comment]
Make sure `babel-plugin-transform-class-properties` is installed
