### ISSUE TITLE
gulp test:client returns Error: 1 at formatError

### ISSUE THREAD

**Issue by lydemeister** [angular-fullstack/generator-angular-fullstack#1748]
Item | Version
----- | -----
generator-angular-fullstack | 3.5.0
Node | 5.5.0
npm | 3.3.12
Operating System | Windows 10

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | SCSS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y

I just created a new project with the specified options. When i run "gulp test:client" I get the following error:

PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)

[11:06:15] 'test:client' errored after 3.09 s
[11:06:15] Error: 1
    at formatError (C:\Users\chris\Desktop\DemoMEAN\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\chris\Desktop\DemoMEAN\node_modules\gulp\bin\gulp.js:195:15)

**Comment by Koslun** [comment]
Getting the same error with similar setups on Ubuntu 15.10 with similar setups:

Item|	Version
------|----------
generator-angular-fullstack|	3.5.0
Node|	4.4.2
npm|	3.3.6

Item|	Answer1|Answer2
------|-----------|------------
Transpiler|	TypeScript |TypeScript
Markup|	HTML|HTML
CSS|	SCSS|SCSS
Router|	ngRouter |ngRouter
Build Tool|	Gulp|Gulp
Client Tests|	Jasmine| Mocha + Chai + Sinon
DB|	Mongoose | Mongoose
Auth|	Y | Y

**Comment by Awk34** [comment]
I'm looking into this. Adding this option to karma helps: `logLevel: 'debug'`.

**Comment by Awk34** [comment]
First issue: `'./tsconfig.client.json'` should be `'./tsconfig.client.test.json'` here: https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/gulpfile.babel(gulp).js#L318

**Comment by Koslun** [comment]
@Awk34: Using the configuration labeled as "Answer 3" above and using the change you mentioned, the tests did now show up but they all fail because of some issue with transpilation I think. 

The errors I'm getting now: 

```javascript
Component: mainComponent
    ✗ should attach a list of things to the controller
	/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4588:53
	forEach@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:322:24
	loadModules@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4548:12
	createInjector@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4470:30
	workFn@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2954:60

	TypeError: undefined is not an object (evaluating 'mainComponent.$onInit') in /home/adam/apps/karma-fullstack-gulp/.tmp/test/app/main/main.controller.spec.js (line 25)
	/home/adam/apps/karma-fullstack-gulp/.tmp/test/app/main/main.controller.spec.js:25:22


  Controller: OauthButtonsCtrl
    ✗ should attach loginOauth
	/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4588:53
	forEach@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:322:24
	loadModules@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4548:12
	createInjector@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4470:30
	workFn@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2954:60

	TypeError: undefined is not an object (evaluating 'OauthButtonsCtrl.loginOauth') in /home/adam/apps/karma-fullstack-gulp/.tmp/test/components/oauth-buttons/oauth-buttons.controller.spec.js (line 16)
	/home/adam/apps/karma-fullstack-gulp/.tmp/test/components/oauth-buttons/oauth-buttons.controller.spec.js:16:32


  Directive: oauthButtons
    ✗ should contain anchor buttons
	/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4588:53
	forEach@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:322:24
	loadModules@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4548:12
	createInjector@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4470:30
	workFn@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2954:60

	/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4588:53
	forEach@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:322:24
	loadModules@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4548:12
	createInjector@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4470:30
	workFn@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2954:60
	inject@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2934:46
	compileDirective@/home/adam/apps/karma-fullstack-gulp/.tmp/test/components/oauth-buttons/oauth-buttons.directive.spec.js:8:15
	/home/adam/apps/karma-fullstack-gulp/.tmp/test/components/oauth-buttons/oauth-buttons.directive.spec.js:19:25

    ✗ should evaluate and bind the classes attribute to scope.classes
	/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4588:53
	forEach@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:322:24
	loadModules@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4548:12
	createInjector@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4470:30
	workFn@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2954:60

	TypeError: Attempted to assign to readonly property. in /home/adam/apps/karma-fullstack-gulp/.tmp/test/components/oauth-buttons/oauth-buttons.directive.spec.js (line 23)
	/home/adam/apps/karma-fullstack-gulp/.tmp/test/components/oauth-buttons/oauth-buttons.directive.spec.js:23:20

    ✗ should bind scope.classes to class names on the anchor buttons
	/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4588:53
	forEach@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:322:24
	loadModules@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4548:12
	createInjector@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4470:30
	workFn@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2954:60

	/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4588:53
	forEach@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:322:24
	loadModules@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4548:12
	createInjector@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular/angular.js:4470:30
	workFn@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2954:60
	inject@/home/adam/apps/karma-fullstack-gulp/client/bower_components/angular-mocks/angular-mocks.js:2934:46
	compileDirective@/home/adam/apps/karma-fullstack-gulp/.tmp/test/components/oauth-buttons/oauth-buttons.directive.spec.js:8:15
	/home/adam/apps/karma-fullstack-gulp/.tmp/test/components/oauth-buttons/oauth-buttons.directive.spec.js:28:25


PhantomJS 2.1.1 (Linux 0.0.0): Executed 5 of 5 (5 FAILED) ERROR (0.046 secs / 0.036 secs)

[20:12:47] 'test:client' errored after 645 ms
[20:12:47] Error: 1
    at formatError (/home/adam/.nvm/versions/node/v4.4.2/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/home/adam/.nvm/versions/node/v4.4.2/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/adam/apps/karma-fullstack-gulp/node_modules/orchestrator/index.js:264:8)
    at /home/adam/apps/karma-fullstack-gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/adam/apps/karma-fullstack-gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/adam/apps/karma-fullstack-gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/home/adam/apps/karma-fullstack-gulp/node_modules/karma/lib/server.js:336:7)
    at Server.<anonymous> (/home/adam/apps/karma-fullstack-gulp/node_modules/karma/lib/server.js:347:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickDomainCallback (node.js:394:17)
```

Looking into the `.tmp` folder after the tests have run the `.tmp/test` directory contains the same `app` and `components` folders that the non-test part does. Meaning it somehow ends with none of the test files still there and the regular source code in its place.

Will try with the aforementioned karma option as well.

**Comment by Awk34** [comment]
@Koslun This is what mine contains
![asdfddd](https://cloud.githubusercontent.com/assets/5545474/14686007/f8507814-0704-11e6-98e9-1df56d13df62.png)

**Comment by Koslun** [comment]
@Awk34 Yours does make a lot more sense, can't really find why my version doesn't look like it yet. Mine is like your `.tmp/app folder`. Will try to post a screen shot.

**Comment by Koslun** [comment]
So here it is:
![tmp-folder](https://cloud.githubusercontent.com/assets/1533205/14686379/b6cd750c-0738-11e6-883b-df73a14c2a4b.png)

**Comment by Koslun** [comment]
Looking at it again it's obvious that the test files are present with the `main.controller.spec.js` file present in the picture and others in the components folder not shown in the picture. 

Deleting the .tmp folder I additionally found the old regular files gone.

The new errors I got were:

```JavaScript
	Error: [$injector:modulerr] Failed to instantiate module karmaFullstackGulpOneApp due to:
	Error: [$injector:modulerr] Failed to instantiate module karmaFullstackGulpOneApp.auth due to:
	Error: [$injector:modulerr] Failed to instantiate module karmaFullstackGulpOneApp.constants due to:
	Error: [$injector:nomod] Module 'karmaFullstackGulpOneApp.constants' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```
Solved by including `'.tmp/app.constant.js',` in the `files` array in `karma.conf.js`.

Where there is a difference between the gulp and grunt version, where the gulp version has this `app.constant.js` file and the grunt version does not.

**Comment by Koslun** [comment]
@Awk34 Unless you already fixed this I made a PR that should fix the remaining issue the same way as my previous post outlines. See PR #1807.
