### ISSUE TITLE
MongoError: not authorized.....

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#1783]
Item | Version
----- | -----
generator-angular-fullstack | 3.5.0
Node | 4.2.6
npm | 3.8.5
Operating System | Windows 10 

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | Jade
CSS | Stylus
Router | ui-router
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB
Auth | Y

After installing with yo and running grunt I receive the the following error message. I have some older projects that worked very well upon a few days, since I receive the same error:
MongoError: not authorized on ngfullstack1-test to execute command { delete: "users", deletes: [ { q: {}, limit: 0 } ], ordered: true }
      at Function.MongoError.create (m:\Websites\Evalu\Angular\yo\ng-full-stack\node_modules\mongoose\node_modules\mongodb-core\lib\error.js:31:11)
      at commandCallback (m:\Websites\Evalu\Angular\yo\ng-full-stack\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:1154:66)
      at bound (domain.js:287:14)
      at runBound (domain.js:300:12)
      at [object Object].Callbacks.emit (m:\Websites\Evalu\Angular\yo\ng-full-stack\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:119:3)
      at [object Object].messageHandler (m:\Websites\Evalu\Angular\yo\ng-full-stack\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:295:23)
      at Socket.<anonymous> (m:\Websites\Evalu\Angular\yo\ng-full-stack\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:285:22)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

**Comment by Awk34** [comment]
I highly doubt that it's anything to do with this project. You probably have invalid Mongo permissions.

**Comment by MarinAngelo** [comment]
You are right, sorry for having posted the issue here. It is definitely a local mongodb problem.
