### ISSUE TITLE
'grunt' failing out of the box.

### ISSUE THREAD

**Issue by sejr** [angular-fullstack/generator-angular-fullstack#1801]
1) Thing API: GET /api/things "before each" hook for "should respond with JSON array":
     Error: expected 200 "OK", got 404 "Not Found"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1525:8)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  2) Thing API: POST /api/things "before each" hook for "should respond with the newly created thing":
     Error: expected 201 "Created", got 404 "Not Found"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at Server.assert (node_modules/supertest/lib/test.js:127:12)
      at emitCloseNT (net.js:1525:8)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  3) Thing API: GET /api/things/:id "before each" hook for "should respond with the requested thing":
     TypeError: Cannot read property '_id' of undefined
      at Context.<anonymous> (thing.integration.js:64:31)

  4) Thing API: PUT /api/things/:id "before each" hook for "should respond with the updated thing":
     TypeError: Cannot read property '_id' of undefined
      at Context.<anonymous> (thing.integration.js:92:31)

  5) Thing API: DELETE /api/things/:id should respond with 204 on successful removal:
     TypeError: Cannot read property '_id' of undefined
      at Context.<anonymous> (thing.integration.js:123:34)

  6) Thing API: DELETE /api/things/:id should respond with 404 when thing does not exist:
     TypeError: Cannot read property '_id' of undefined
      at Context.<anonymous> (thing.integration.js:135:34)

Item | Version
----- | -----
generator-angular-fullstack | Latest
Node | 5.10.1
npm | 3.8.3
Operating System | Debian
etc | etc

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | CSS
Router | ui-router
Build Tool | Grunt
Client Tests | Mocha
DB | SQL
Auth | Y
etc | etc

**Comment by Awk34** [comment]
what does your `server/routes.js` look like?

**Comment by sejr** [comment]
Regenerating the project seemed to resolve this issue. I think it may have been a problem with my Internet connection at the time of calling the generator.
