### ISSUE TITLE
OAuth facebook fail 

### ISSUE THREAD

**Issue by Demonium** [angular-fullstack/generator-angular-fullstack#1861]
I have an error when I try to use facebook for OAuth connection, see the log error below
```
Executing (default): SELECT `data` FROM `Sessions` AS `Session` WHERE `Session`.`sid` = 'uUxnfvlzcmVURwjLir2-6qhaOwPFx4FK' LIMIT 1;
GET /auth/facebook 302 0.556 ms - 0
Executing (default): SELECT `data` FROM `Sessions` AS `Session` WHERE `Session`.`sid` = 'uUxnfvlzcmVURwjLir2-6qhaOwPFx4FK' LIMIT 1;
Executing (default): SELECT `_id`, `name`, `email`, `role`, `password`, `provider`, `salt`, `facebook`, `twitter`, `google`, `github`, `createdAt`, `updatedAt` FROM `Users` AS `User` WHERE (`User`.`facebook`#>>'{id}') = '1050767364959615' LIMIT 1;
SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
    at Query.formatError (/home/djo/apps/pensieve/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/home/djo/apps/pensieve/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/djo/apps/pensieve/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/djo/apps/pensieve/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:535:20)
From previous event:
    at Query.run (/home/djo/apps/pensieve/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
    at /home/djo/apps/pensieve/node_modules/sequelize/lib/sequelize.js:844:20
    at /home/djo/apps/pensieve/node_modules/retry-as-promised/index.js:38:21
From previous event:
    at retryAsPromised (/home/djo/apps/pensieve/node_modules/retry-as-promised/index.js:27:10)
    at /home/djo/apps/pensieve/node_modules/sequelize/lib/sequelize.js:843:12
From previous event:
    at Promise.then (/home/djo/apps/pensieve/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAll (/home/djo/apps/pensieve/node_modules/sequelize/lib/model.js:1410:6)
    at Model.findOne (/home/djo/apps/pensieve/node_modules/sequelize/lib/model.js:1542:34)
    at Strategy._verify (passport.js:15:10)
    at /home/djo/apps/pensieve/node_modules/passport-oauth2/lib/strategy.js:193:24
    at /home/djo/apps/pensieve/node_modules/passport-facebook/lib/strategy.js:181:5
    at passBackControl (/home/djo/apps/pensieve/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/home/djo/apps/pensieve/node_modules/oauth/lib/oauth2.js:143:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I'm using mysql-server 5.7 needed for JSON type

**Comment by Demonium** [comment]
Same as #1778
