### ISSUE TITLE
Some console error just after doing a clean generation

### ISSUE THREAD

**Issue by deniz946** [angular-fullstack/generator-angular-fullstack#1862]
Hello, im getting this just after a clean yo generation of project, on grunt serve... and i don't know what it means, any help please?

```
Warning: a promise was created in a handler but was not returned from it
    at MongoStore.touch (/home/deniz946/Desktop/test/node_modules/connect-mongo/src/index.js:273:18)
    at ServerResponse.end (/home/deniz946/Desktop/test/node_modules/express-session/index.js:301:15)
    at ServerResponse.send (/home/deniz946/Desktop/test/node_modules/express/lib/response.js:204:10)
    at ServerResponse.json (/home/deniz946/Desktop/test/node_modules/express/lib/response.js:249:15)
    at thing.controller.js:19:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at index (thing.controller.js:65:6)
    at Layer.handle [as handle_request] (/home/deniz946/Desktop/test/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/deniz946/Desktop/test/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/deniz946/Desktop/test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/deniz946/Desktop/test/node_modules/express/lib/router/layer.js:95:5)
    at /home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:330:12)
    at next (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:176:3)
    at router (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/deniz946/Desktop/test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:312:13)
    at /home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:330:12)
    at next (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/home/deniz946/Desktop/test/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:312:13)
    at /home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:330:12)
    at next (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:271:10)
    at logger (/home/deniz946/Desktop/test/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/home/deniz946/Desktop/test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:312:13)
    at /home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/deniz946/Desktop/test/node_modules/express/lib/router/index.js:330:12)
```

**Comment by Awk34** [comment]
You can safely ignore this warning for now. Bluebird 3 will warn you whenever "a promise was created in a handler but was not returned from it", so whenever a new promise is created in a function, but that promise is not returned from that function.

You can see the issue for connect-mongo here: https://github.com/kcbanner/connect-mongo/issues/214

**Comment by chovy** [comment]
I'm still getting this.
