### ISSUE TITLE
You need to update yo to at least 1.7.1

### ISSUE THREAD

**Issue by canercak** [angular-fullstack/generator-angular-fullstack#1938]
I'm getting this error on angular-fullstack version even my yo version is on 1.8.3

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ERROR: You need to update yo to at least 1.7.1 (npm i -g yo)
    at /Users/apple/.node/lib/node_modules/generator-angular-fullstack/generators/generator-base.js:51:15
    at tryCatcher (/Users/apple/.node/lib/node_modules/generator-angular-fullstack/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/apple/.node/lib/node_modules/generator-angular-fullstack/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/apple/.node/lib/node_modules/generator-angular-fullstack/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/apple/.node/lib/node_modules/generator-angular-fullstack/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/apple/.node/lib/node_modules/generator-angular-fullstack/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/apple/.node/lib/node_modules/generator-angular-fullstack/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/apple/.node/lib/node_modules/generator-angular-fullstack/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/apple/.node/lib/node_modules/generator-angular-fullstack/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
You have new mail in /var/mail/apple
canermac-3:posluga2 apple$ 

 - [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel / TypeScript
Markup | HTML / Jade
CSS | CSS / LESS / SCSS / Stylus
Router | ngRoute / ui-router
Build Tool | Grunt / Gulp
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

**Comment by Awk34** [comment]
It works fine for me

**Comment by Koslun** [comment]
You're getting this when you do what? And you're kinda supposed to fill in the details in those two tables at the end of your answer.

**Comment by Awk34** [comment]
@Koslun relevent commit: 58c9dbf51d6bb0db736a7aa0befd0a573b2f52f0

**Comment by Koslun** [comment]
@Awk34 Ok, looking at the code it does seem like it *should* work. Switched stdout for the aforementioned version that should work and tested it out a bit using https://tonicdev.com/npm/semver just to be sure:

```javascript
var semver = require("semver")

var validVersion = semver.satisfies(semver.clean('1.8.3'), '>= 1.7.1')

console.log('Version is valid: ' + validVersion); //outputs "Version is valid: true"
```

So if there's a bug it'd likely be with how the command is executed and what is finally sent as `stdout `. Figure it's also something that's more likely to only be an issue on some operating systems and why it might not have been caught earlier.

So posting your specs might help a lot @canercak (operating system, npm, node and generator version in particular).

**Comment by yalishizhude** [comment]
OS: win10
node: v6.2.0
npm: 3.8.9
yo: 1.8.4
![unnamed qq screenshot20160601101035](https://cloud.githubusercontent.com/assets/3870098/15696227/19140154-27e1-11e6-837d-635dc50cc8c4.jpg)

**Comment by Awk34** [comment]
@yalishizhude I just tried with the same versions:

```bash
$ node -v
v6.2.0

$ npm -v
3.8.9

$ yo --version
1.8.4

$ yo angular-fullstack

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I create an AngularJS app with an Express server.

# Client

? What would you like to write scripts with? (Use arrow keys)
> Babel
  TypeScript
```

**Comment by Koslun** [comment]
@yalishizhude Does `yo doctor` give you any issues? Would just try just re-installing yeoman and angular-fullstack.

Is there some mysterious difference with picking angular-fullstack in the list of generators when running `yo` compared to doing `yo angular-fullstack`?

**Comment by Awk34** [comment]
@Koslun I tried with just running `yo` and selecting the generator; still worked.

**Comment by Awk34** [comment]
@Koslun #1944

**Comment by Koslun** [comment]
Not sure how to reproduce this issue but with @Awk34's PR #1944 we can see the output and thus probably determine what's wrong.

**Comment by Awk34** [comment]
Install 3.7.5 and post what it shows

**Comment by Awk34** [comment]
Closed due to inactivity
