### ISSUE TITLE
Facebook Authentication FacebookTokenError: Error validating client secret, still logged in

### ISSUE THREAD

**Issue by seanlarge** [angular-fullstack/generator-angular-fullstack#1954]
- [ x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 6.0.0
npm | 3.8.9
Operating System | OS X 10.10.5

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | SCSS 
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB | SQL
Auth | Y 

Hi,

I registered my app with facebook. I run gulp serve and start my application, click sign up, click log in with facebook. I am redirected, enter my email and password then am redirected to this error:

```
FacebookTokenError: Error validating client secret.
   at Strategy.parseErrorResponse (/Users/sea2574595/dev/Haystack-Development/node_modules/passport-facebook/lib/strategy.js:196:12)
   at Strategy.OAuth2Strategy._createOAuthError (/Users/sea2574595/dev/Haystack-Development/node_modules/passport-oauth2/lib/strategy.js:367:16)
   at /Users/sea2574595/dev/Haystack-Development/node_modules/passport-oauth2/lib/strategy.js:166:45
   at /Users/sea2574595/dev/Haystack-Development/node_modules/oauth/lib/oauth2.js:177:18
   at passBackControl (/Users/sea2574595/dev/Haystack-Development/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/Users/sea2574595/dev/Haystack-Development/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:926:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)
```

However if I return to the main page, I see in the console that I get logged in from the code that was provided from facebook: 
```

<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '1582628798702650',
    cookie     : true,  // enable cookies to allow the server to access 
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.5' // use graph api version 2.5
  });

  // Now that we've initialized the JavaScript SDK, we call 
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    console.log('FACEBOOK LOGIN STATUS-------->', response);
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>
```

The nav bar provided by the yoeman generator (where it says, 'hi, test user') does not acknowledge that I am signed in though, and when looking in the sqlite db I do not see that any information was saved. 
I can still create a user and/or login at that point as well. 
Then only way for me to log out of facebook is to delete the cookies. 

I provided the secret key that was given to me from facebook along with my app id in ALL the config/env files:

local.env.**.js:

 ```
FACEBOOK_ID: '<my-app-id>',
  FACEBOOK_SECRET: '<my-secret-key>',
```

Does anyone know where this issue may be coming from? I am a bit lost.

**Comment by seanlarge** [comment]
**update**

I am receiving different errors now on the facebook callback. after clicking 'log in with facebook' I see : 

```
SequelizeDatabaseError: SQLITE_ERROR: unrecognized token: "#"
    at Query.formatError (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
    at afterExecute (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at replacement (/Users/sea2574595/dev/Haystack-Development/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.errBack (/Users/sea2574595/dev/Haystack-Development/node_modules/sqlite3/lib/sqlite3.js:16:21)
From previous event:
    at executeSql (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:103:19)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Promise.then (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/promise.js:21:17)
    at Database.<anonymous> (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:278:14)
    at /Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:98:19
From previous event:
    at Query.run (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:96:13)
    at /Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/sequelize.js:843:20
    at /Users/sea2574595/dev/Haystack-Development/node_modules/retry-as-promised/index.js:38:21
From previous event:
    at retryAsPromised (/Users/sea2574595/dev/Haystack-Development/node_modules/retry-as-promised/index.js:27:10)
    at /Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/sequelize.js:842:12
From previous event:
    at Promise.then (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAll (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/model.js:1387:6)
    at Model.findOne (/Users/sea2574595/dev/Haystack-Development/nodeGET /auth/facebook/callback?code=AQCA1hqVa0qn7UuvsgNQtsO6Yf9bBwwa16m7SKptKf81_zkApOnevSgUkfiEawoX9Tyyy5ZosfudlCSIOxV8VceSeHSbD2DthUQazd_KUYdHVCgjVxRktY65vFGLz9gGg_JOBzREmpwiDPeqdvSaHOhf13lyg0P1_ol18ZsyVmErKEfvHKzQ3VP1ag5l_nnRSU3vQ4T28uR5pZDgCp6B8gE-G8jajo8rgu-Bh9TwgZ6BgOu_E3-z3o7BWC-KNGM8yiNM5A2kWrYUrKq7W3B8cAZni6zOm2umsFUhcuL6OPueDsL8TWCTJvvFX8Th15sRm6c 500 692.980 ms - -
_modules/sequelize/lib/model.js:1519:34)
    at Strategy._verify (passport.js:17:10)
    at /Users/sea2574595/dev/Haystack-Development/node_modules/passport-oauth2/lib/strategy.js:193:24
    at /Users/sea2574595/dev/Haystack-Development/node_modules/passport-facebook/lib/strategy.js:181:5
    at passBackControl (/Users/sea2574595/dev/Haystack-Development/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/Users/sea2574595/dev/Haystack-Development/node_modules/oauth/lib/oauth2.js:143:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
The scaffold passport strategy seems to work and is getting called up until the model is called in 'server/auth/facebook/passport.js' When logging the profile in the 'setup function' if shows my facebook information is reaching my server but not being created:


```
import passport from 'passport';
import {Strategy as FacebookStrategy} from 'passport-facebook';


export function setup(User, config) {
  passport.use(new FacebookStrategy({
    clientID: config.facebook.clientID,
    clientSecret: config.facebook.clientSecret,
    callbackURL: config.facebook.callbackURL,
    profileFields: [
      'displayName',
      'emails'
    ]
  },
  function(accessToken, refreshToken, profile, done) {
    **console.log('profile-------------->', profile);**
    User.find({where:{'facebook.id': profile.id}})
      .then(user => {
            console.log('USER----------->', user);
         **above log never gets hit**
        if (user) {
      console.log('found user');
          return done(null, user);
        }

        user = User.build({
          name: profile.displayName,
          email: profile.emails[0].value,
          role: 'user',
          provider: 'facebook',
          facebook: profile._json
        });
        user.save()
          .then(user =>  done(null, user))
          .catch(err => done(err));
      })
      .catch(err => done(err));
  }));
}
import passport from 'passport';
import {Strategy as FacebookStrategy} from 'passport-facebook';
import {User} from'../../sqldb';

export function setup(User, config) {
  passport.use(new FacebookStrategy({
    clientID: config.facebook.clientID,
    clientSecret: config.facebook.clientSecret,
    callbackURL: config.facebook.callbackURL,
    profileFields: [
      'displayName',
      'emails'
    ]
  },
  function(accessToken, refreshToken, profile, done) {
    console.log('profile-------------->', profile);
    User.find({where:{'facebook.id': profile.id}})
      .then(user => {
            console.log('USER----------->', user);

        if (user) {
      console.log('found user');
          return done(null, user);
        }

        user = User.build({
          name: profile.displayName,
          email: profile.emails[0].value,
          role: 'user',
          provider: 'facebook',
          facebook: profile._json
        });
        user.save()
          .then(user =>  done(null, user))
          .catch(err => done(err));
      })
      .catch(err => done(err));
  }));
}
```

**Comment by Koslun** [comment]
Please mention which version of the generator you are using. It is very vital to debugging.

You can see the version in the `.yo-rc` file in your generated project and at the top of your gulp file.

**Comment by Awk34** [comment]
What's the `profile.id`? Does it contain a `#`? Maybe Sequelize / SQLite doesn't like it

**Comment by seanlarge** [comment]
@Koslun  I updated to the latest version, deleted the generated project and scaffold again. My problem now is in regards to my latest comment to which @Awk34 addressed.

@Awk34 when I console.log profile.id it is a long hash, did not see any '#' i'm wondering if this have anything to do with the fact that facebook also returns a json object in _profile (which contains all your prorfile info)? I need to check when I get home so I can show you the complete object. But will that store in sequelize/ sqlite as jason? no right?


Also, I still get logged in by facebook, and can see so in the console when i return to the app. However the angular-fullstack app does not see that i am logged in. 

are there any docs on how the sqlite db is saving data in the angular-fullstack repo? All my data is wiped despite turning seeding off (i even go as far as commenting out the whole seed file and the database still populates....)

Thank you for the response!

**Comment by Awk34** [comment]
The JSON response is stored [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.4/templates/app/server/auth(auth)/facebook(facebookAuth)/passport.js#L28)
```js
          facebook: profile._json
```

**Comment by seanlarge** [comment]
@Awk34  result of logging profile:
```

{ id: 'my-id',
  username: undefined,
  displayName: 'my-display-name',
  name: 
   { familyName: undefined,
     givenName: undefined,
     middleName: undefined },
  gender: undefined,
  profileUrl: undefined,
  emails: [ { value: 'my-email' } ],
  provider: 'facebook',
  _raw: '{"name":"name","email":"email","id":"id"}',
  _json: 
   { name: 'my-name',
     email: 'my-email',
     id: 'my-id' } }
```

I don't see a # sing in there and am not sure where the sqlite error is coming from. Any ideas on where else to debug? here is the full error output again:
```

SequelizeDatabaseError: SQLITE_ERROR: unrecognized token: "#"
    at Query.formatError (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
    at afterExecute (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at replacement (/Users/sea2574595/dev/Haystack-Development/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.errBack (/Users/sea2574595/dev/Haystack-Development/node_modules/sqlite3/lib/sqlite3.js:16:21)
From previous event:
    at executeSql (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:103:19)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Promise.then (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/promise.js:21:17)
    at Database.<anonymous> (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:278:14)
    at /Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:98:19
From previous event:
    at Query.run (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/dialects/sqlite/query.js:96:13)
    at /Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/sequelize.js:843:20
    at /Users/sea2574595/dev/Haystack-Development/node_modules/retry-as-promised/index.js:38:21
From previous event:
    at retryAsPromised (/Users/sea2574595/dev/Haystack-Development/node_modules/retry-as-promised/index.js:27:10)
    at /Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/sequelize.js:842:12
From previous event:
    at Promise.then (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAll (/Users/sea2574595/dev/Haystack-Development/node_modules/sequelize/lib/model.js:1387:6)
    at Model.findOne (/Users/sea2574595/dev/Haystack-Development/nodeGET /auth/facebook/callback?code=AQAM6ku9mVPMa8Fm5MH_UQUHxdoVcUj3LDwoxHvlLcIhQguXt7YF0PPTuP8a0voyAo_pwOxlzmmLJ8VbIpXaY8fkdrx5f1-YLDyfq8xCkYoaFeTIKGxgRdCa7jKAOS46QYF4i0V1yrnZnq8ZbCLuD-0nWVUWMPeqVc4ckCGRVxso5IrgC0vAxjgQIwtmd_4MJVoKEgzypYO6KB0k6dRbcFPSwTOR8sxxD_6gId_8dBX1QQTbnU8hEVLSSjaAEerLj_cEmDX_c6P0NakovlUAiP5S7g9XHJnJ3cSnde2Kf8-57T5vnfWRup_Ka-ZEWFy3faE 500 1160.237 ms - -
_modules/sequelize/lib/model.js:1519:34)
    at Strategy._verify (passport.js:18:10)
    at /Users/sea2574595/dev/Haystack-Development/node_modules/passport-oauth2/lib/strategy.js:193:24
    at /Users/sea2574595/dev/Haystack-Development/node_modules/passport-facebook/lib/strategy.js:181:5
    at passBackControl (/Users/sea2574595/dev/Haystack-Development/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/Users/sea2574595/dev/Haystack-Development/node_modules/oauth/lib/oauth2.js:143:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by seanlarge** [comment]
in regards to the link in your template : 

```
<% if (filters.mongooseModels) { %>user = new User({<% }
           if (filters.sequelizeModels) { %>user = User.build({<% } %>
          name: profile.displayName,
          email: profile.emails[0].value,
          role: 'user',
          provider: 'facebook',
          facebook: profile._json
        });
```

your putting json in the 'facebook' attribute of 'User' right? with sqlite?

**Comment by Awk34** [comment]
Hmmm, okay that helps. This might be a bit more complicated than I first thought. It looks like you might have to strip that hash before it's passed to Passport.

**Comment by seanlarge** [comment]
looking into passport now

**Comment by seanlarge** [comment]
@Awk34 I'm all out of ideas...I put log statements in every part of the auth/ folder. it looks like sqlite takes a dump then the callback fails? still getting this error: 

```
SequelizeDatabaseError: SQLITE_ERROR: unrecognized token: "#"
    at Query.formatError (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
    at afterExecute (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at replacement (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.errBack (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sqlite3/lib/sqlite3.js:16:21)
From previous event:
    at executeSql (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/dialects/sqlite/query.js:103:19)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at Promise.then (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/promise.js:21:17)
    at Database.<anonymous> (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/dialects/sqlite/query.js:278:14)
    at /Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/dialects/sqlite/query.js:98:19
From previous event:
    at Query.run (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/dialects/sqlite/query.js:96:13)
    at /Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/sequelize.js:843:20
    at /Users/sea2574595/dev/Haystack-Develompment/node_modules/retry-as-promised/index.js:38:21
From previous event:
    at retryAsPromised (/Users/sea2574595/dev/Haystack-Develompment/node_modules/retry-as-promised/index.js:27:10)
    at /Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/sequelize.js:842:12
From previous event:
    at Promise.then (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAll (/Users/sea2574595/dev/Haystack-Develompment/node_modules/sequelize/lib/model.js:1387:6)
    at Model.findOne (/Users/sea2574595/dev/Haystack-DGET /auth/facebook/callback?code=AQBQe7dPAsn9KmlCnmdZEy1Ntss3RnBFWMFWbOQtkVlatNkv0IvgR_8x1zaE5bvAd5z4c059Et6CJTTJ3PBhGhZ7ejYKdOA8osSPWSRQHdzOnwB0dvxLoFpGzhAhjiq5yIZyc4XGsZloCG5EcMFFdZh6nKdVYF7DqdDV663S658jKu8ev8B2k9Lp6qgd4cPmgOAdEz97u-QzRSY5u1MMe_va_I6kleEF4Dg2dsN3aMqij-HG4L2Wvqi_HhDYVaH_PiMw0Zktxkz3SkAukvpUidDUjR6-a3Ua2YFt412v9VtjTxTzhYxBblUUQJs9B09ac70 500 524.787 ms - -
evelompment/node_modules/sequelize/lib/model.js:1519:34)
    at Strategy._verify (passport.js:15:10)
    at /Users/sea2574595/dev/Haystack-Develompment/node_modules/passport-oauth2/lib/strategy.js:193:24
    at /Users/sea2574595/dev/Haystack-Develompment/node_modules/passport-facebook/lib/strategy.js:181:5
    at passBackControl (/Users/sea2574595/dev/Haystack-Develompment/node_modules/oauth/lib/oauth2.js:125:9)
    at IncomingMessage.<anonymous> (/Users/sea2574595/dev/Haystack-Develompment/node_modules/oauth/lib/oauth2.js:143:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by hamsil** [comment]
I got the same error with Google Authentication and sqlite. If I setup the project completely identical but use mongodb instead of sqlite everything works fine.

Item|Version
----|------
generator-angular-fullstack|3.7.5
Node|6.2.1
npm|3.9.3
Operating System|Ubuntu 16.04 64bit

Item|Answer
----|------
Transpiler|TrueScript
Markup|Jade
CSS|SASS
Router|ui-router
DB|Sequelize(doesn't work), Mongoose (works fine)
Build Tool|Gulp
Client Tests|Mocha
Auth|Y

`http://localhost:9000/auth/google/callback?code=4/IByxbS5zIlzb_tUXcNUaZcQWcVPTjJ3SgJdtD12ERVQ#` is called after entering user and password at Google and returns the error:
```
SequelizeDatabaseError: SQLITE_ERROR: unrecognized token: "#"
   at Query.formatError (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
   at afterExecute (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
   at replacement (/home/vagrant/TestAppBernd/node_modules/sqlite3/lib/trace.js:20:31)
   at Statement.errBack (/home/vagrant/TestAppBernd/node_modules/sqlite3/lib/sqlite3.js:16:21)
From previous event:
   at executeSql (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/dialects/sqlite/query.js:103:19)
   at tryOnImmediate (timers.js:543:15)
   at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
   at Promise.then (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/promise.js:21:17)
   at Database.<anonymous> (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/dialects/sqlite/query.js:278:14)
   at /home/vagrant/TestAppBernd/node_modules/sequelize/lib/dialects/sqlite/query.js:98:19
From previous event:
   at Query.run (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/dialects/sqlite/query.js:96:13)
   at /home/vagrant/TestAppBernd/node_modules/sequelize/lib/sequelize.js:843:20
   at /home/vagrant/TestAppBernd/node_modules/retry-as-promised/index.js:38:21
From previous event:
   at retryAsPromised (/home/vagrant/TestAppBernd/node_modules/retry-as-promised/index.js:27:10)
   at /home/vagrant/TestAppBernd/node_modules/sequelize/lib/sequelize.js:842:12
From previous event:
   at Promise.then (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/promise.js:21:17)
   at Model.findAll (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/model.js:1387:6)
   at Model.findOne (/home/vagrant/TestAppBernd/node_modules/sequelize/lib/model.js:1519:34)
   at Strategy._verify (passport.js:11:10)
   at /home/vagrant/TestAppBernd/node_modules/passport-oauth2/lib/strategy.js:193:24
   at /home/vagrant/TestAppBernd/node_modules/passport-google-oauth20/lib/strategy.js:122:5
   at passBackControl (/home/vagrant/TestAppBernd/node_modules/oauth/lib/oauth2.js:125:9)
   at IncomingMessage.<anonymous> (/home/vagrant/TestAppBernd/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:926:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9) 
```

**Comment by pkboy** [comment]
Since you mentioned it works with Mongoose but not SQL, one possible issue is when it calls User.find:

`User.find({where:{'facebook.id': profile.id}})`

That matches the id value from the facebook column which works fine if it's saved as a JSON object, unfortunately in SQL it's just a String type and not JSON so it can't find it properly. One way around is to have another column solely for the Facebook ID and use that to match the profile.id that Facebook sends when it hits your callback.

**Comment by seanlarge** [comment]
I thought it had something to do with the JSON object ...

Sean Large
954.465.8910

**Comment by CGavrila** [comment]
Still getting this with `generator-angular-fullstack@4.1.0`. :(

**Comment by CGavrila** [comment]
Looks like the problem is here:
```
Executing (default): SELECT `_id`, `name`, `email`, `role`, `password`, `provider`, `salt`, `facebook`, `twitter`, `google`, `github` FROM `Users` AS `User` WHERE (`User`.`facebook`#>>'{id}') = '1429278267100090' LIMIT 1;
```
I'm assuming that `#>>` in the `WHERE` clause is the issue. I haven't really found what the proper syntax is for SQLite + JSON, but it looks like the issue lies with Sequelize? Can anyone else approve or disprove what I just said?
