### ISSUE TITLE
Deployment to IBM Bluemix Issue with Babel

### ISSUE THREAD

**Issue by Gregoyle** [angular-fullstack/generator-angular-fullstack#1987]
I'm trying to deploy the angular full stack application to IBM's PaaS Bluemix but am receiving the error:
```
2016-06-18T11:43:40.93-0300 [App/0]      ERR SyntaxError: Unexpected reserved word
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at exports.runInThisContext (vm.js:53:16)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at Module._compile (module.js:373:25)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at Object.Module._extensions..js (module.js:416:10)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at Module.load (module.js:343:32)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at Function.Module._load (module.js:300:12)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at Module.require (module.js:353:17)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at require (internal/module.js:12:17)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/server/index.js:12:28)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at Module._compile (module.js:409:26)
2016-06-18T11:43:40.93-0300 [App/0]      ERR     at Object.Module._extensions..js (module.js:416:10)

```
When the application tries to start. I've read enough to understand that this is an issue with babel. 
My babelrc contains:
```
 {
     "presets": ["es2015"],
     "plugins": ["transform-class-properties"]
-}
```
I've tried adding this to my server's app.js:

```
require('babel-register')({
  "presets": ["es2015"]
});
```
Any help or direction would be appreciated.

- [ X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | v6.2.1
Node | v6.2.1
npm | 3.9.3
Operating System | OS X 10 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS 
Router | ngRoute
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB 
Auth | Y
etc | etc

**Comment by Gregoyle** [comment]
In case anyone stumbles upon this, be sure that you're actually deploying your /dist/ folder. I was so used to deploying from the root of the application that I forgot that "grunt build" produced a deployment ready version in your /dist/ folder.
