### ISSUE TITLE
SQLite can't find sync property

### ISSUE THREAD

**Issue by minchomilev** [angular-fullstack/generator-angular-fullstack#1990]
server\config\seed.js:17
Thing.sync().then(function () {
     ^

Hi, what I am missing - when I try to use generator with sqlite I am getting this error:

TypeError: Cannot read property 'sync' of undefined
    at Object.<anonymous> (seed.js:11:1)
    at Module._compile (module.js:541:32)
    at loader (C:\booking\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\booking\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (app.js:13:22)
    at Module._compile (module.js:541:32)
    at loader (C:\booking\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\booking\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

With mongodb everything is fine

**Comment by minchomilev** [comment]
With today version of Angular Fullstack it is working  :)
