### ISSUE TITLE
Gulp Test has error in events.js:160

### ISSUE THREAD

**Issue by gabrielkunkel** [angular-fullstack/generator-angular-fullstack#2028]
When I run "gulp serve" it serves up the page just fine. "gulp test" does this:

```
[11:52:40] Requiring external module babel-register
(node:15763) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[11:52:42] Using gulpfile ~/WebstormProjects/tawkc/gulpfile.babel.js
[11:52:42] Starting 'test'...
[11:52:42] Starting 'test:server'...
[11:52:42] Starting 'env:all'...
[11:52:42] Finished 'env:all' after 42 ms
[11:52:42] Starting 'env:test'...
[11:52:42] Finished 'env:test' after 480 μs
[11:52:42] Starting 'mocha:unit'...


  Thing API Router:

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE 0.0.0.0:9000
  at Object.exports._errnoException (util.js:953:11)
  at exports._exceptionWithHostPort (util.js:976:20)
  at Server._listen2 (net.js:1253:14)
  at listen (net.js:1289:10)
  at net.js:1399:9
  at _combinedTickCallback (internal/process/next_tick.js:77:11)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

No bueno. It *is* weird that the error happens right after, "[11:52:42] Starting 'mocha:unit'..." when I have selected jasmine. But is it that mocha is used for backend?

- [ X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | just updated to latest
Node | 6.2.0
npm | 3.8.9
Operating System | OS X 10 el capitan

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmin
DB | MongoDB
Auth | Y + Facebook

**Comment by gabrielkunkel** [comment]
I solved this by shutting down the 'gulp serve' and then running 'gulp test.' So, it doesn't seem like I can run tests while the server is running. That's a bummer.

**Comment by Awk34** [comment]
Yes, this is because the server tests are testing your regular server. The server tests start up a new instance of your server to make requests against it. You *could* tell the server to use a different port if it's being started by tests.

As for the `mocha:unit` part: The prompt you answered about which test framework to use was for client tests. Jasmine has not been implemented for server tests.
