### ISSUE TITLE
gulp build failed

### ISSUE THREAD

**Issue by dimkonomis** [angular-fullstack/generator-angular-fullstack#2042]
Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 5.11.1
Operating System | Ubuntu 14.04.4 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | CSS 
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB | MongoDB 
Auth | Y 

Hello, i'm trying to run gulp build and i'm getting the following error

> events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: spawn /root/Test/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
  at exports._errnoException (util.js:893:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
  at onErrorNT (internal/child_process.js:348:16)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Any ideas how to fix this?

**Comment by dimkonomis** [comment]
I reinstalled jpegtran but it keeps failing. I ended up removing 'build:images' from gulp to get it work.
Thank you for your answer

**Comment by Awk34** [comment]
I suggest `rm -rf node_modules` and then `npm i`
