### ISSUE TITLE
Test showing Error for Things?

### ISSUE THREAD

**Issue by atodicebear** [angular-fullstack/generator-angular-fullstack#2047]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 4.4.5
npm | 3.9.6
Operating System | Windows7
yo | 1.8.4

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML 
CSS |  SCSS 
Router | ui-router
Build Tool | Gulp
Client Tests | Mocha
DB |  SQL
Auth | Y 
etc | etc

Hey,
for fun i did the npm test run just to check which Errors he would throw.
The Standard User is passing but Things is not ?
  Thing API Router:
    V should return an express router instance
    GET /api/things
      19) should route to thing.controller.index
    GET /api/things/:id
      20) should route to thing.controller.show
    POST /api/things
      21) should route to thing.controller.create
    PUT /api/things/:id
      22) should route to thing.controller.update
    PATCH /api/things/:id
      23) should route to thing.controller.update
    DELETE /api/things/:id
      24) should route to thing.controller.destroy

What is the Problem because I did not Delete the Files?
The Code is still in thing.controler.js/index.js
What have i to do to change this Error ?
Because its thrwoing the same for my Generated Tables
  Thing API Router:
    V should return an express router instance
    GET /api/things
      19) should route to thing.controller.index
    GET /api/things/:id
      20) should route to thing.controller.show
    POST /api/things
      21) should route to thing.controller.create
    PUT /api/things/:id
      22) should route to thing.controller.update
    PATCH /api/things/:id
      23) should route to thing.controller.update
    DELETE /api/things/:id
      24) should route to thing.controller.destroy

**Comment by Awk34** [comment]
Do you have a relelvent stack trace?

**Comment by atodicebear** [comment]
Where can i get it to Post it here ?

**Comment by Awk34** [comment]
Your console *should* show stack traces for failed tests

**Comment by atodicebear** [comment]
I have copied whole output in .txt file.
At the end it says just npm ERR! test failed 24 Errors or something.
The Trace is in the File i think.

[error.txt](https://github.com/angular-fullstack/generator-angular-fullstack/files/358804/error.txt)

**Comment by Awk34** [comment]
Okay, so each of your tests has the same exact error:

```
AssertionError: expected spy to have been called exactly once, but it was called 0 times
    at doAsserterAsyncAndAddThen (C:\Users\alex_kreuder\github\eucondictionary\node_modules\chai-as-promised\lib\chai-as-promised.js:296:33)
    at [object Object].<anonymous> (C:\Users\alex_kreuder\github\eucondictionary\node_modules\chai-as-promised\lib\chai-as-promised.js:286:25)
    at [object Object].Object.defineProperty.get (C:\Users\alex_kreuder\github\eucondictionary\node_modules\chai\lib\chai\utils\overwriteProperty.js:50:37)
    at Context.<anonymous> (C:\Users\alex_kreuder\github\eucondictionary\server\api\dict_key\index.spec.js:40:77)
    at callFn (C:\Users\alex_kreuder\github\eucondictionary\node_modules\mocha\lib\runnable.js:326:21)
    at Test.Runnable.run (C:\Users\alex_kreuder\github\eucondictionary\node_modules\mocha\lib\runnable.js:319:7)
    at Runner.runTest (C:\Users\alex_kreuder\github\eucondictionary\node_modules\mocha\lib\runner.js:422:10)
    at C:\Users\alex_kreuder\github\eucondictionary\node_modules\mocha\lib\runner.js:528:12
    at next (C:\Users\alex_kreuder\github\eucondictionary\node_modules\mocha\lib\runner.js:342:14)
    at C:\Users\alex_kreuder\github\eucondictionary\node_modules\mocha\lib\runner.js:352:7
    at next (C:\Users\alex_kreuder\github\eucondictionary\node_modules\mocha\lib\runner.js:284:14)
    at Immediate._onImmediate (C:\Users\alex_kreuder\github\eucondictionary\node_modules\mocha\lib\runner.js:320:5)
```

**Comment by atodicebear** [comment]
In Console only just npm test.
Never done test before so nothing changed somewhere.
Looked up in Thing.integration.js and others integration.js on server side.
There stays allways expect....
here some example
```
'use strict';

var app = require('../..');
import request from 'supertest';

var newThing;

describe('Thing API:', function() {

  describe('GET /api/mains', function() {
    var things;

    beforeEach(function(done) {
      request(app)
        .get('/api/mains')
        .expect(200)
        .expect('Content-Type', /json/)
        .end((err, res) => {
          if (err) {
            return done(err);
          }
          things = res.body;
          done();
        });
    });

    it('should respond with JSON array', function() {
      expect(things).to.be.instanceOf(Array);
    });

  });

  describe('POST /api/things', function() {
    beforeEach(function(done) {
      request(app)
        .post('/api/things')
        .send({
          name: 'New Thing',
          info: 'This is the brand new thing!!!'
        })
        .expect(201)
        .expect('Content-Type', /json/)
        .end((err, res) => {
          if (err) {
            return done(err);
          }
          newThing = res.body;
          done();
        });
    });

    it('should respond with the newly created thing', function() {
      expect(newThing.name).to.equal('New Thing');
      expect(newThing.info).to.equal('This is the brand new thing!!!');
    });

  });
```
Is it that what you wanted to ask ?
In index.spec.js
the same
```
'use strict';

var proxyquire = require('proxyquire').noPreserveCache();

var thingCtrlStub = {
  index: 'thingCtrl.index',
  show: 'thingCtrl.show',
  create: 'thingCtrl.create',
  update: 'thingCtrl.update',
  destroy: 'thingCtrl.destroy'
};

var routerStub = {
  get: sinon.spy(),
  put: sinon.spy(),
  patch: sinon.spy(),
  post: sinon.spy(),
  delete: sinon.spy()
};

// require the index with our stubbed out modules
var thingIndex = proxyquire('./index.js', {
  'express': {
    Router: function() {
      return routerStub;
    }
  },
  './thing.controller': thingCtrlStub
});

describe('Thing API Router:', function() {

  it('should return an express router instance', function() {
    expect(thingIndex).to.equal(routerStub);
  });

  describe('GET /api/things', function() {

    it('should route to thing.controller.index', function() {
      expect(routerStub.get
        .withArgs('/', 'thingCtrl.index')
        ).to.have.been.calledOnce;
    });

  });
```
