### ISSUE TITLE
error on default install

### ISSUE THREAD

**Issue by chovy** [angular-fullstack/generator-angular-fullstack#2053]
```

Warning: a promise was created in a handler but was not returned from it
    at MongoStore.touch (/Users/username/projects/tmp/test/my-new-project/node_modules/connect-mongo/src/index.js:279:18)
    at ServerResponse.end (/Users/username/projects/tmp/test/my-new-project/node_modules/express-session/index.js:332:15)
    at ServerResponse.send (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/response.js:205:10)
    at ServerResponse.json (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/response.js:250:15)
    at thing.controller.js:19:30
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at index (thing.controller.js:65:6)
    at Layer.handle [as handle_request] (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/layer.js:95:5)
    at /Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:312:13)
    at /Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:312:13)
    at /Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:271:10)
    at livereload (/Users/username/projects/tmp/test/my-new-project/node_modules/connect-livereload/index.js:97:14)
    at Layer.handle [as handle_request] (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:312:13)
    at /Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/username/projects/tmp/test/my-new-project/node_modules/express/lib/router/index.js:330:12)
```

**Comment by Awk34** [comment]
A: That says "Warning", not "Error"
B: Search previous issues before creating new ones: #1507, #1810, #1862, #1882, #1930,

**Comment by chovy** [comment]
Warning with a stack trace? That's a new one.

**Comment by svict4** [comment]
Did you find a fix for this @chovy? Console being spammed with warnings isn't a great look, especially on a fresh install. :sweat:

**Comment by chovy** [comment]
Nope. Apparently its expected?
