### ISSUE TITLE
SyntaxError: Unexpected reserved word "import" when Deploying to Heroku

### ISSUE THREAD

**Issue by jroth01** [angular-fullstack/generator-angular-fullstack#2103]
Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 6.2.2
npm | 3.9.5
Operating System | OS X 10.11.5
etc | 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS
Router | ngRoute
Client Tests | Jasmine
DB | MongoDB
Auth | Y 
etc | 

When I try and deploy my angular-fullstack app to Heroku, I keep getting the following error messages in my logs. I'm not sure how to fix the issue.

2016-08-01T14:26:05.211786+00:00 heroku[web.1]: State changed from crashed to starting
2016-08-01T14:26:09.807426+00:00 heroku[web.1]: Starting process with command `npm start`
2016-08-01T14:26:13.400127+00:00 app[web.1]: > epb-web-app@0.0.0 start /app
2016-08-01T14:26:13.400128+00:00 app[web.1]: > node server
2016-08-01T14:26:13.400129+00:00 app[web.1]: 
2016-08-01T14:26:13.400114+00:00 app[web.1]: 
2016-08-01T14:26:13.665763+00:00 app[web.1]: /app/server/app.js:7
2016-08-01T14:26:13.665780+00:00 app[web.1]: import express from 'express';
2016-08-01T14:26:13.665781+00:00 app[web.1]: ^^^^^^
2016-08-01T14:26:13.665788+00:00 app[web.1]:     at Module.load (module.js:343:32)
2016-08-01T14:26:13.665788+00:00 app[web.1]:     at Function.Module._load (module.js:300:12)
2016-08-01T14:26:13.665789+00:00 app[web.1]:     at Module.require (module.js:353:17)
2016-08-01T14:26:13.665781+00:00 app[web.1]: 
2016-08-01T14:26:13.665787+00:00 app[web.1]:     at Module._compile (module.js:373:25)
2016-08-01T14:26:13.665786+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2016-08-01T14:26:13.665785+00:00 app[web.1]: SyntaxError: Unexpected reserved word
2016-08-01T14:26:13.665787+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-08-01T14:26:13.665791+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:416:10)
2016-08-01T14:26:13.721628+00:00 app[web.1]: npm ERR! Linux 3.13.0-85-generic
2016-08-01T14:26:13.665790+00:00 app[web.1]:     at require (internal/module.js:12:17)
2016-08-01T14:26:13.721632+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-08-01T14:26:13.665791+00:00 app[web.1]:     at Module._compile (module.js:409:26)
2016-08-01T14:26:13.721634+00:00 app[web.1]: npm ERR! npm  v2.15.9
2016-08-01T14:26:13.665790+00:00 app[web.1]:     at Object.<anonymous> (/app/server/index.js:12:28)
2016-08-01T14:26:13.691645+00:00 app[web.1]: 
2016-08-01T14:26:13.721633+00:00 app[web.1]: npm ERR! node v4.4.7
2016-08-01T14:26:13.730532+00:00 app[web.1]: npm ERR! Exit status 1
2016-08-01T14:26:13.730528+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-08-01T14:26:13.730534+00:00 app[web.1]: npm ERR! Failed at the epb-web-app@0.0.0 start script 'node server'.
2016-08-01T14:26:13.730531+00:00 app[web.1]: npm ERR! epb-web-app@0.0.0 start: `node server`
2016-08-01T14:26:13.730534+00:00 app[web.1]: npm ERR! This is most likely a problem with the epb-web-app package,
2016-08-01T14:26:13.730533+00:00 app[web.1]: npm ERR! 
2016-08-01T14:26:13.730535+00:00 app[web.1]: npm ERR! not with npm itself.
2016-08-01T14:26:13.730536+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-08-01T14:26:13.731727+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-08-01T14:26:13.731381+00:00 app[web.1]: npm ERR!     node server
2016-08-01T14:26:13.732075+00:00 app[web.1]: npm ERR!     npm bugs epb-web-app
2016-08-01T14:26:13.733477+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-08-01T14:26:13.734875+00:00 app[web.1]: npm ERR! 
2016-08-01T14:26:13.735875+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-08-01T14:26:13.735228+00:00 app[web.1]: npm ERR!     npm owner ls epb-web-app
2016-08-01T14:26:13.744523+00:00 app[web.1]: 
2016-08-01T14:26:13.744861+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-08-01T14:26:13.745031+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-08-01T14:26:13.835469+00:00 heroku[web.1]: Process exited with status 1
2016-08-01T14:26:13.850274+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by Koslun** [comment]
If there is an actual issue it is imperative that you actually fill in what version and configuration you're using. There are many issues fixed between versions and a very start difference between the different major versions.

So please add what version of the generator you're using.

Either way it looks like the code has not been built before being run. I.e. running `gulp build` and using what's in the `dist` folder. Probably have to revise your deployment strategy.

**Comment by jroth01** [comment]
I updated my post to indicate that I'm using angular fullstack generator v 3.7.5.

**Comment by Koslun** [comment]
Those import statements should not be turning up in your production code. Should rather see a bunch of `var` statements with `require'`s, different from your original code as it's been transpiled by `babel`. This could happen if you try to start the project directly without building it, as you then have ES2015/ES6 Javascript code that can't run natively on NodeJS without a Babel run-time (as is done when we serve the application with `gulp`)

So as I said above you either are not deploying the correct files. Need to use the files in the dist folder that you get after a `gulp` or `grunt build`.

**Comment by arkdelkaos** [comment]
Look at `https://dashboard.heroku.com/apps/`your-project`/logs`: could you paste the output?  
Sometimes there is interesting info ;)

**Comment by catchlui** [comment]
Any luck with the below issue ?

**Comment by Awk34** [comment]
Closed due to inactivity
