### ISSUE TITLE
endpoint generator breaking on blank project

### ISSUE THREAD

**Issue by Climax777** [angular-fullstack/generator-angular-fullstack#2155]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.1
Node | 6.3.1
npm | 3.10.6
yo | 1.8.4
Operating System | Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Jasmine
DB | MongoDB
Auth | Y / N
Auth Types | only local

This is happening to me with generator-angular-fullstack@4.0.1 brand new project:
```
yo angular-fullstack:endpoint atm
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'sequelizeModels' of undefined
    at Generator.prompting (/home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/generators/endpoint/index.js:118:30)
    at Object.<anonymous> (/home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:439:23)
    at /home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/node_modules/run-async/index.js:26:25
    at /home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/node_modules/run-async/index.js:25:19
    at /home/pieter/.nvm/versions/node/v6.3.1/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:440:9
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by Climax777** [comment]
Sorry I was working in the wrong folder
