### ISSUE TITLE
express middelware Route

### ISSUE THREAD

**Issue by abdoul-aziz** [angular-fullstack/generator-angular-fullstack#2183]
Error: No default engine was specified and no extension was provided.
   at new View (C:\Users\hacking\stageLipro\projet\node_modules\express\lib\view.js:62:11)
   at EventEmitter.render (C:\Users\hacking\stageLipro\projet\node_modules\express\lib\application.js:569:12)
   at ServerResponse.render (C:\Users\hacking\stageLipro\projet\node_modules\express\lib\response.js:960:7)
   at C:\Users\hacking\stageLipro\projet\server.js:32:9
   at Layer.handle [as handle_request] (C:\Users\hacking\stageLipro\projet\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\hacking\stageLipro\projet\node_modules\express\lib\router\route.js:131:13)
   at C:\Users\hacking\stageLipro\projet\server.js:29:10
   at Layer.handle [as handle_request] (C:\Users\hacking\stageLipro\projet\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Users\hacking\stageLipro\projet\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Users\hacking\stageLipro\projet\node_modules\express\lib\router\route.js:112:3)

**Comment by abdoul-aziz** [comment]
please someone help me. i dont what is a problem

**Comment by abdoul-aziz** [comment]
there is possible to use this a middelware Route for render html extenmssion page like this index.html
