### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by manmon42** [angular-fullstack/generator-angular-fullstack#2233]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.0.5
Node | 6.2.2
npm | 3.3.10
Operating System | Windows 10
Yeoman | 1.8.5

Item | Answer
----- | -----
Markup | HTML 
CSS | CSS
Router | ngRoute

Hey, so when I try and run any of the sub-generators I get.
`TypeError: Cannot read property 'indexOf' of undefined`

Here's the full stacktrace.
```
D:\Desktop\whenDoesItEnd>yo angular-fullstack:route switch
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'indexOf' of undefined
    at Generator.hasExtension (D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\generators\script-base.js:45:28)
    at Generator.exports.default (D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\generators\script-base.js:48:25)
    at Generator.initializing (D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\generators\route\index.js:37:35)
    at Object.<anonymous> (D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\node_modules\yeoman-generator\lib\base.js:431:23)
    at D:\Desktop\whenDoesItEnd\node_modules\run-async\index.js:26:25
    at D:\Desktop\whenDoesItEnd\node_modules\run-async\index.js:25:19
    at D:\Desktop\whenDoesItEnd\node_modules\generator-ng-component\node_modules\yeoman-generator\lib\base.js:432:9
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by Awk34** [comment]
From the stack trace it looks like this is an issue with generator-ng-component. Please file a bug report there.

**Comment by jagzviruz** [comment]
I am facing this issue with v4.1.4
