### ISSUE TITLE
NPM install error | Error: Cannot find module './src/init'

### ISSUE THREAD

**Issue by apank** [angular-fullstack/generator-angular-fullstack#2296]
```
> optipng-bin@3.1.2 postinstall /Users/apank/Desktop/test/node_modules/optipng-bin
> node lib/install.js

module.js:339
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/apank/Desktop/test/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm WARN install:optipng-bin@3.1.2 optipng-bin@3.1.2 postinstall: `node lib/install.js`
npm WARN install:optipng-bin@3.1.2 Exit status 1

> jpegtran-bin@3.1.0 postinstall /Users/apank/Desktop/test/node_modules/jpegtran-bin
> node lib/install.js

module.js:339
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/apank/Desktop/test/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
npm WARN install:jpegtran-bin@3.1.0 jpegtran-bin@3.1.0 postinstall: `node lib/install.js`
npm WARN install:jpegtran-bin@3.1.0 Exit status 1

> gifsicle@3.0.4 postinstall /Users/apank/Desktop/test/node_modules/gifsicle
> node lib/install.js

module.js:339
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/apank/Desktop/test/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
npm WARN install:gifsicle@3.0.4 gifsicle@3.0.4 postinstall: `node lib/install.js`
npm WARN install:gifsicle@3.0.4 Exit status 1
```

**Comment by idpbond** [comment]
https://github.com/floridoo/gulp-sourcemaps/issues/243 @ @

**Comment by apank** [comment]
Thanks, I was able to resolve the issue differently. Somehow the link for node got messed up, I resolved it by running the following

`brew doctor
brew link node
brew link --overwrite node`
