### ISSUE TITLE
Errors in production

### ISSUE THREAD

**Issue by RonAlmog** [angular-fullstack/generator-angular-fullstack#2379]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 6.9.1
npm | 3.10.8
Operating System | Ubuntu 16.4 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
etc | etc

created prod version with grunt:build.
deployed to server (digital ocean).
ran npm install --production on the project's root folder on server.
created .bash_profile with this in it:  export NODE_ENV=production
verified with: echo $NODE_ENV
and the answer is production, as should be.
when i run: node index.js , it is running. 
but when i try to run it with pm2, i get tons of errors, and it wont work. here is the beginning of the error log:
```
    at Function.Module._load (module.js:438:3)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ron/www.website.com/server/app.js:17:26)
    at Module._compile (module.js:570:32)
Error: Cannot find module './undefined.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ron/server/config/environment/index.js:71:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ron/www.website.com/server/app.js:17:26)
    at Module._compile (module.js:570:32)
Error: Cannot find module './undefined.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ron/server/config/environment/index.js:71:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ron/www.website.com/server/app.js:17:26)
    at Module._compile (module.js:570:32)
```

Any idea what could go wrong?
my pm2 command is like this:
sudo pm2 start index.js --watch

**Comment by Awk34** [comment]
https://stackoverflow.com/questions/34897875/how-do-i-set-linux-environment-variables-so-that-pm2-can-see-them-for-node-js-ap#34898026

**Comment by RonAlmog** [comment]
Fantastic. Yes, it did solve the problem. thanks!

sudo **-E** pm2 start index.js
