### ISSUE TITLE
Getting CastError: Cast to ObjectId failed 

### ISSUE THREAD

**Issue by ajai-sandy** [angular-fullstack/generator-angular-fullstack#2442]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.8.0
Node | 4.4.0
npm | 2.14.20
Operating System | Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | CSS 
Router | ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
SocketIO | Y 

Hi, I did a fresh install, I tried to login using default credentials but unfortunately am not able to login, getting the following error in my terminal

```
CastError: Cast to ObjectId failed for value "586d2fd0d9a89f219f994d97" at path "_id" for model "User"
    at MongooseError.CastError (/home/ajai/Projects/test/node_modules/mongoose/lib/error/cast.js:26:11)
    at ObjectId.cast (/home/ajai/Projects/test/node_modules/mongoose/lib/schema/objectid.js:147:13)
    at ObjectId.castForQuery (/home/ajai/Projects/test/node_modules/mongoose/lib/schema/objectid.js:187:15)
    at cast (/home/ajai/Projects/test/node_modules/mongoose/lib/cast.js:229:32)
    at Query.cast (/home/ajai/Projects/test/node_modules/mongoose/lib/query.js:2752:12)
    at Query.findOne (/home/ajai/Projects/test/node_modules/mongoose/lib/query.js:1353:10)
    at /home/ajai/Projects/test/node_modules/mongoose/lib/query.js:2310:21
From previous event:
    at Query.exec (/home/ajai/Projects/test/node_modules/mongoose/lib/query.js:2304:17)
    at Middleware_Common_Object.<anonymous> (/home/ajai/Projects/test/server/auth/auth.service.js:34:35)
    at next (/home/ajai/Projects/test/node_modules/composable-middleware/lib/composable-middleware.js:59:18)
    at /home/ajai/Projects/test/node_modules/express-jwt/lib/index.js:122:7
    at /home/ajai/Projects/test/node_modules/async/lib/async.js:52:16
    at Immediate._onImmediate (/home/ajai/Projects/test/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
GET /api/users/me 500 32.642 ms - -
```
Help in this really appreciated, thanks in advance.

**Comment by Awk34** [comment]
Hmm, looks like a DB issue. Try hosing your DB, updating your Mongo, updating your mongo npm modules (mongoose, mongodb, etc). If all else fails, I'd ask the mongoose folks.

**Comment by ajai-sandy** [comment]
I am currently running 2 projects with v3.7.5 & grunt in my localhost, am able to login and there is no issue with it. I tried installing v3.7.6 & v3.8.0 with gulp then I am getting the above mentioned error. I tried with a different computer as well, but still am able to replicate the issue on these two version of v3.7.6 & v3.8.0 with gulp.

**Comment by ajai-sandy** [comment]
> Solution

The issue is not with the mongodb, its due to the node version of my system, updated from v4 to v7 now it works perfect for me ..
