### ISSUE TITLE
ERROR in ./client/polyfills.ts - File has unknown extension (alpha)

### ISSUE THREAD

**Issue by klemensz** [angular-fullstack/generator-angular-fullstack#2503]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-alpha.4
Node | v6.9.4
npm | 3.10.10
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML
CSS | Sass
Router | ngRoute
Client Tests | Mocha
DB | MongoDB
Auth | Y

When running `$ npm install -g yo generator-angular-fullstack@alpha` and then `$ yo angular-fullstack` with the settings from above, and then gulp server, I get the following errors:

```
nikita2:some-project klemens$ gulp serve
[12:54:54] Requiring external module babel-register
[12:55:05] Using gulpfile ~/dev/my_projects/some-project/gulpfile.babel.js
(node:34231) DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:34231) DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
[12:55:05] Starting 'serve'...
[12:55:05] Starting 'clean:tmp'...
[12:55:05] Starting 'lint:scripts'...
[12:55:05] Starting 'lint:scripts:client'...
[12:55:05] Starting 'lint:scripts:server'...
[12:55:05] Starting 'inject'...
[12:55:05] Starting 'inject:scss'...
[12:55:05] Starting 'copy:fonts:dev'...
[12:55:05] Starting 'env:all'...
[12:55:05] Finished 'env:all' after 17 ms
[12:55:05] Starting 'typings'...
[12:55:07] Finished 'clean:tmp' after 1.61 s
[12:55:07] [gulp-tslint] error (no-trailing-whitespace) polyfills.ts[29, 1]: trailing whitespace
[12:55:07] [gulp-tslint] error (no-use-before-declare) polyfills.ts[21, 5]: variable 'ENV' used before declaration
[12:55:07] [gulp-tslint] error (whitespace) polyfills.ts[21, 3]: missing whitespace
[12:55:07] [gulp-tslint] error (whitespace) polyfills.ts[25, 3]: missing whitespace
[12:55:08] gulp-inject Nothing to inject into app.scss.
[12:55:08] Finished 'inject:scss' after 3.02 s
[12:55:08] Finished 'inject' after 3.03 s
[12:55:08] [gulp-tslint] error (no-unused-variable) app/app.module.ts[39, 20]: Unused import: 'ErrorHandler'
[12:55:08] [gulp-tslint] error (no-unused-variable) app/app.module.ts[45, 3]: Unused import: 'RequestOptionsArgs'
[12:55:08] [gulp-tslint] error (whitespace) app/app.module.ts[65, 3]: missing whitespace
[12:55:09] [gulp-tslint] error (whitespace) app/app.ts[9, 3]: missing whitespace
[12:55:09] [gulp-tslint] error (whitespace) app/app.ts[19, 3]: missing whitespace
[12:55:09] [gulp-tslint] error (no-use-before-declare) app/polyfills.ts[5, 5]: variable 'ENV' used before declaration
[12:55:09] [gulp-tslint] error (whitespace) app/polyfills.ts[5, 3]: missing whitespace
[12:55:09] [gulp-tslint] error (whitespace) app/polyfills.ts[9, 3]: missing whitespace
[12:55:09] [gulp-tslint] error (curly) components/util.ts[65, 5]: if statements must be braced
[12:55:09] [gulp-tslint] error (whitespace) components/util.ts[65, 7]: missing whitespace
[12:55:09] [gulp-tslint] error (no-unused-variable) app/account/account.module.ts[7, 10]: Unused import: 'STATES'
[12:55:09] [gulp-tslint] error (no-unused-variable) app/account/account.routes.ts[1, 10]: Unused import: 'LoginComponent'
[12:55:09] [gulp-tslint] error (no-unused-variable) app/account/account.routes.ts[2, 10]: Unused import: 'SignupComponent'
[12:55:09] [gulp-tslint] error (no-unused-variable) app/account/account.routes.ts[3, 10]: Unused import: 'SettingsComponent'
[12:55:09] [gulp-tslint] error (no-unused-variable) app/account/account.routes.ts[4, 10]: Unused import: 'AuthService'
[12:55:09] [gulp-tslint] error (no-trailing-whitespace) app/account/index.ts[3, 42]: trailing whitespace
[12:55:09] [gulp-tslint] error (no-unused-variable) app/admin/admin.module.ts[5, 24]: Unused import: 'Routes'
[12:55:09] [gulp-tslint] error (no-unused-variable) app/admin/admin.routes.ts[1, 10]: Unused import: 'AdminComponent'
[12:55:10] [gulp-tslint] error (whitespace) app/main/main.component.ts[40, 7]: missing whitespace
[12:55:10] [gulp-tslint] error (no-unused-variable) components/auth/auth.service.ts[2, 10]: Unused import: 'Response'
[12:55:10] [gulp-tslint] error (no-unused-variable) components/auth/auth.service.ts[6, 10]: Unused import: 'Observable'
[12:55:10] [gulp-tslint] error (whitespace) components/auth/auth.service.ts[32, 7]: missing whitespace
[12:55:10] Finished 'copy:fonts:dev' after 4.85 s
[12:55:10] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[7, 7]: missing whitespace
[12:55:10] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[11, 7]: missing whitespace
[12:55:10] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[13, 11]: missing whitespace
[12:55:10] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[25, 11]: missing whitespace
[12:55:10] [gulp-tslint] error (whitespace) components/auth/user.service.ts[30, 17]: missing whitespace
[12:55:10] [gulp-tslint] error (whitespace) components/auth/user.service.ts[35, 17]: missing whitespace
[12:55:10] [gulp-tslint] error (whitespace) components/auth/user.service.ts[40, 17]: missing whitespace
[12:55:10] [gulp-tslint] error (whitespace) components/auth/user.service.ts[45, 17]: missing whitespace
[12:55:10] [gulp-tslint] error (semicolon) components/navbar/navbar.component.ts[29, 7]: Missing semicolon
[12:55:11] [gulp-tslint] error (whitespace) components/socket/socket.service.ts[39, 9]: missing whitespace
[12:55:11] [gulp-tslint] error (whitespace) app/account/settings/settings.component.ts[34, 7]: missing whitespace
[12:55:11] Finished 'typings' after 5.58 s
[12:55:11] 
/Users/klemens/dev/my_projects/some-project/server/index.js
  4:11  warning  Unexpected use of process.env  no-process-env
  4:34  warning  Unexpected use of process.env  no-process-env

/Users/klemens/dev/my_projects/some-project/server/config/express.js
  68:50  warning  Unexpected use of process.env  no-process-env

/Users/klemens/dev/my_projects/some-project/server/api/thing/thing.controller.js
   29:7  warning  Avoid using Function.prototype.apply, instead use Reflect.apply     prefer-reflect
   89:5  warning  Avoid using the delete keyword, instead use Reflect.deleteProperty  prefer-reflect
  100:5  warning  Avoid using the delete keyword, instead use Reflect.deleteProperty  prefer-reflect

/Users/klemens/dev/my_projects/some-project/server/api/user/user.model.js
  194:15  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  195:18  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  197:22  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  198:18  warning  Use the rest parameters instead of 'arguments'  prefer-rest-params
  238:14  warning  Unexpected sync method: 'pbkdf2Sync'            no-sync

/Users/klemens/dev/my_projects/some-project/server/config/environment/shared.js
  4:8  warning  Unexpected use of process.env  no-process-env
  5:9  warning  Unexpected use of process.env  no-process-env

✖ 13 problems (0 errors, 13 warnings)

[12:55:11] Finished 'lint:scripts:server' after 5.79 s
[12:55:11] Finished 'lint:scripts:client' after 5.83 s
[12:55:11] Finished 'lint:scripts' after 5.83 s
[12:55:11] Starting 'start:server'...
[12:55:11] Finished 'start:server' after 49 ms
[12:55:11] Starting 'start:client'...
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/klemens/dev/my_projects/some-project/server/**/*
[nodemon] starting `node server`
(node:34240) DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:34240) DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
Express server listening on 9000, in development mode
[BS] Proxying: http://localhost:9000
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.2.169:3000
 --------------------------------------
          UI: http://localhost:3002
 UI External: http://192.168.2.169:3002
 --------------------------------------
Error: ENOENT: no such file or directory, stat '/Users/klemens/dev/my_projects/some-project/client/index.html'
    at Error (native)
[12:55:20] Finished 'start:client' after 9.15 s
[12:55:20] Starting 'watch'...
[12:55:20] Finished 'watch' after 106 ms
[12:55:20] Finished 'serve' after 15 s
Error: ENOENT: no such file or directory, stat '/Users/klemens/dev/my_projects/some-project/client/index.html'
    at Error (native)
GET / 404 425.026 ms - 161
(node:34240) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest
GET / 404 12.283 ms - 161
Error: ENOENT: no such file or directory, stat '/Users/klemens/dev/my_projects/some-project/client/index.html'
    at Error (native)
Error: ENOENT: no such file or directory, stat '/Users/klemens/dev/my_projects/some-project/client/index.html'
    at Error (native)
GET / 404 11.281 ms - 161
GET / 404 10.961 ms - 161
Error: ENOENT: no such file or directory, stat '/Users/klemens/dev/my_projects/some-project/client/index.html'
    at Error (native)
Error: ENOENT: no such file or directory, stat '/Users/klemens/dev/my_projects/some-project/client/index.html'
    at Error (native)
Error: ENOENT: no such file or directory, stat '/Users/klemens/dev/my_projects/some-project/client/index.html'
    at Error (native)
Error: ENOENT: no such file or directory, stat '/Users/klemens/dev/my_projects/some-project/client/index.html'
    at Error (native)
GET / 404 20.566 ms - 161
GET / 404 20.541 ms - 161
GET / 404 20.474 ms - 161
GET / 404 19.284 ms - 161
finished populating users
webpack: wait until bundle finished: /
Error: Debug Failure. False expression: File  has unknown extension. Error: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3168:23)
    at Object.fail (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3173:19)
    at Object.extensionFromPath (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3315:15)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62598:46
    at Array.map (native)
    at resolveModuleNamesWorker (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62592:141)
    at resolveModuleNamesReusingOldState (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62719:24)
    at processImportedModules (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63571:35)
    at findSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63481:17)
    at processSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63384:27)
    at processRootFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63271:13)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62620:60
    at Object.forEach (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:1293:30)
    at Object.createProgram (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62620:16)
    at synchronizeHostData (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:79368:33)
    at Object.getProgram (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:79468:13)
    at State.updateProgram (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/host.js:241:42)
    at _callee3$ (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:177:35)
    at tryCatch (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:116:21)
    at fulfilled (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:31:32)
Error: Cannot resolve module 'ui-router-ng2' in /Users/klemens/dev/my_projects/some-project/client/components
    Required in /Users/klemens/dev/my_projects/some-project/client/components/directives.module.ts Error: Cannot resolve module 'ui-router-ng2' in /Users/klemens/dev/my_projects/some-project/client/components
    Required in /Users/klemens/dev/my_projects/some-project/client/components/directives.module.ts
    at ResolutionError.Error (native)
    at new ResolutionError (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/deps.js:515:88)
    at /Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/deps.js:340:37
webpack done hook
Hash: 924489ee5769f550f56e
Version: webpack 1.14.0
Time: 4212ms
               Asset     Size  Chunks             Chunk Names
    vendor.bundle.js   580 kB       0  [emitted]  vendor
vendor.bundle.js.map   690 kB       0  [emitted]  vendor
../client/index.html  1.28 kB          [emitted]  

ERROR in ./client/polyfills.ts
Module build failed: Error: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3168:23)
    at Object.fail (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3173:19)
    at Object.extensionFromPath (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3315:15)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62598:46
    at Array.map (native)
    at resolveModuleNamesWorker (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62592:141)
    at resolveModuleNamesReusingOldState (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62719:24)
    at processImportedModules (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63571:35)
    at findSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63481:17)
    at processSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63384:27)
    at processRootFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63271:13)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62620:60
    at Object.forEach (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:1293:30)
    at Object.createProgram (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62620:16)
    at synchronizeHostData (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:79368:33)
    at Object.getProgram (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:79468:13)
    at State.updateProgram (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/host.js:241:42)
    at _callee3$ (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:177:35)
    at tryCatch (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:116:21)
    at fulfilled (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:31:32)

ERROR in ./client/app/app.ts
Module build failed: Error: Cannot resolve module 'ui-router-ng2' in /Users/klemens/dev/my_projects/some-project/client/components
    Required in /Users/klemens/dev/my_projects/some-project/client/components/directives.module.ts
    at ResolutionError.Error (native)
    at new ResolutionError (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/deps.js:515:88)
    at /Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/deps.js:340:37
Child html-webpack-plugin for "../client/index.html":
                   Asset     Size  Chunks       Chunk Names
    ../client/index.html  21.7 kB       0       
webpack: Failed to compile.
webpack: Compiling...
webpack: wait until bundle finished: /vendor.bundle.js
Error: Debug Failure. False expression: File  has unknown extension.
Error: Debug Failure. False expression: File  has unknown extension. Error: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3168:23)
    at Object.fail (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3173:19)
    at Object.extensionFromPath (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3315:15)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62598:46
    at Array.map (native)
    at resolveModuleNamesWorker (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62592:141)
    at resolveModuleNamesReusingOldState (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62719:24)
    at processImportedModules (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63571:35)
    at findSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63481:17)
    at processSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63384:27)
    at processRootFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63271:13)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62620:60
    at Object.forEach (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:1293:30)
    at Object.createProgram (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62620:16)
    at synchronizeHostData (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:79368:33)
    at Object.getProgram (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:79468:13)
    at State.emit (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/host.js:264:46)
    at transform (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:203:48)
    at _callee3$ (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:258:42)
    at tryCatch (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:116:21)
    at fulfilled (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:31:32)
Error: Cannot resolve module 'ui-router-ng2' in /Users/klemens/dev/my_projects/some-project/client/components
    Required in /Users/klemens/dev/my_projects/some-project/client/components/directives.module.ts Error: Cannot resolve module 'ui-router-ng2' in /Users/klemens/dev/my_projects/some-project/client/components
    Required in /Users/klemens/dev/my_projects/some-project/client/components/directives.module.ts
    at ResolutionError.Error (native)
    at new ResolutionError (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/deps.js:515:88)
    at /Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/deps.js:340:37
webpack done hook
Hash: 924489ee5769f550f56e
Version: webpack 1.14.0
Time: 730ms
               Asset    Size  Chunks       Chunk Names
    vendor.bundle.js  580 kB       0       vendor
vendor.bundle.js.map  690 kB       0       vendor

ERROR in ./client/polyfills.ts
Module build failed: Error: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3168:23)
    at Object.fail (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3173:19)
    at Object.extensionFromPath (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3315:15)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62598:46
    at Array.map (native)
    at resolveModuleNamesWorker (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62592:141)
    at resolveModuleNamesReusingOldState (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62719:24)
    at processImportedModules (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63571:35)
    at findSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63481:17)
    at processSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63384:27)
    at processRootFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63271:13)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62620:60
    at Object.forEach (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:1293:30)
    at Object.createProgram (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62620:16)
    at synchronizeHostData (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:79368:33)
    at Object.getProgram (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:79468:13)
    at State.emit (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/host.js:264:46)
    at transform (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:203:48)
    at _callee3$ (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:258:42)
    at tryCatch (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:299:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/klemens/dev/my_projects/some-project/node_modules/regenerator-runtime/runtime.js:116:21)
    at fulfilled (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/index.js:31:32)

ERROR in ./client/app/app.ts
Module build failed: Error: Cannot resolve module 'ui-router-ng2' in /Users/klemens/dev/my_projects/some-project/client/components
    Required in /Users/klemens/dev/my_projects/some-project/client/components/directives.module.ts
    at ResolutionError.Error (native)
    at new ResolutionError (/Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/deps.js:515:88)
    at /Users/klemens/dev/my_projects/some-project/node_modules/awesome-typescript-loader/dist.babel/deps.js:340:37
Child html-webpack-plugin for "../client/index.html":
                   Asset     Size  Chunks       Chunk Names
    ../client/index.html  21.7 kB       0       
webpack: Failed to compile.
[default] Checking started in a separate process...
/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3168
                throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
                ^

Error: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3168:23)
    at Object.fail (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3173:19)
    at Object.extensionFromPath (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:3315:15)
    at /Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62598:46
    at Array.map (native)
    at resolveModuleNamesWorker (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62592:141)
    at resolveModuleNamesReusingOldState (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:62719:24)
    at processImportedModules (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63571:35)
    at findSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63481:17)
    at processSourceFile (/Users/klemens/dev/my_projects/some-project/node_modules/typescript/lib/typescript.js:63384:27)
^C
```

**Comment by Awk34** [comment]
This should be fixed on the HEAD of _canary_. Update your `awesome-typescript-loader` to something in the `2.x.x` range.

**Comment by braxtondiggs** [comment]
Was having this same issue. Just make sure you have typescript 1.8.10 installed:
`npm install typescript@1.8.10`
