### ISSUE TITLE
Unable to compile new projects node-gyp and iltorb issues

### ISSUE THREAD

**Issue by monsonjeremy** [angular-fullstack/generator-angular-fullstack#2522]
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.4
Node | 7.7.3
npm | 4.4.1
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML 
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB 
Auth | Y
socket.io | no

Upon trying to compile a new project I am unable to get the generator to create a project scaffold and get it up and running. 

upon running yo angular-fullstack I receive this error: 

```
> iltorb@1.0.13 install /Users/USER/Desktop/forecast-me/node_modules/iltorb
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config -c import platform; print(platform.python_version());
gyp ERR! stack Usage: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config [--prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--help]
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:210:12)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:191:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:513:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/USER/Desktop/forecast-me/node_modules/iltorb
gyp ERR! node -v v7.7.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iltorb@1.0.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iltorb@1.0.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.
```

and then i follow it up by running gulp serve and get this error: 

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'shrink-ray'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/USER/Desktop/forecast-me/server/config/express.js:10:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/USER/Desktop/forecast-me/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/USER/Desktop/forecast-me/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/USER/Desktop/forecast-me/server/app.js:24:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/USER/Desktop/forecast-me/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/USER/Desktop/forecast-me/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by Awk34** [comment]
See https://github.com/nodejs/node-gyp#installation

**Comment by MayhemYDG** [comment]
Iltorb now offers pre-built binaries, this should be fixed.

**Comment by Awk34** [comment]
@MayhemYDG excellent!

**Comment by infrarosso78** [comment]
i guess it is a problem of version mismatch. I had the same issue in production (ubuntu 16) but it was ok in development (macosx).
I had to remove gulp-node-inspector from package json
then
to manually install
node-gyp@3.6.2, nan@2.5.1, iltorb@1.0.13, node-zopfli@1.4.0
this combination of version worked after 12 hours of terrible headache!
Hope it will help someone.
