### ISSUE TITLE
Test Fails After new Controller Generation

### ISSUE THREAD

**Issue by benmarten** [angular-fullstack/generator-angular-fullstack#2543]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | master
Node | 6.10.1
npm | 3.10.10
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | Sass
Router | ngRoute
Client Tests |  Mocha
DB | MongoDB
Auth | Y

Tested with brand new project.

`yo angular-fullstack:controller myController`
`gulp test`

Fails with: 

```
[10:51:05] Starting 'test:client'...
17 04 2017 10:51:10.068:INFO [karma]: Karma v0.13.22 server started at http://localhost:9000/
17 04 2017 10:51:10.072:INFO [launcher]: Starting browser PhantomJS
17 04 2017 10:51:10.890:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket W3WQ-3FkQx0-RVlvAAAA with id 79196321
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: Object is not a constructor (evaluating 'module('testApp.myController')')
  at /Users/ben/dev/test/spec.js:49894

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.168 secs / 0 secs)

[10:51:11] 'test:client' errored after 5.62 s
[10:51:11] Error: 1
  at formatError (/Users/ben/.config/yarn/global/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
  at Gulp.<anonymous> (/Users/ben/.config/yarn/global/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
  at emitOne (events.js:101:20)
  at Gulp.emit (events.js:188:7)
  at Gulp.Orchestrator._emitTaskDone (/Users/ben/dev/test/node_modules/orchestrator/index.js:264:8)
  at /Users/ben/dev/test/node_modules/orchestrator/index.js:275:23
  at finish (/Users/ben/dev/test/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/ben/dev/test/node_modules/orchestrator/lib/runTask.js:29:3)
  at /Users/ben/dev/test/gulpfile.babel.js:390:9
  at removeAllListeners (/Users/ben/dev/test/node_modules/karma/lib/server.js:336:7)
  at Server.<anonymous> (/Users/ben/dev/test/node_modules/karma/lib/server.js:347:9)
  at Server.g (events.js:291:16)
  at emitNone (events.js:91:20)
  at Server.emit (events.js:185:7)
  at emitCloseNT (net.js:1558:8)
  at _combinedTickCallback (internal/process/next_tick.js:77:11)
  at process._tickDomainCallback (internal/process/next_tick.js:128:9)

[10:51:11] 'test' errored after 7.19 s
[10:51:11] Error in plugin 'run-sequence(test:client)'
Message:
    1
Stack:
  at finish (/Users/ben/dev/test/node_modules/run-sequence/index.js:56:13)
  at Gulp.onError (/Users/ben/dev/test/node_modules/run-sequence/index.js:67:4)
  at emitOne (events.js:101:20)
  at Gulp.emit (events.js:188:7)
  at Gulp.Orchestrator._emitTaskDone (/Users/ben/dev/test/node_modules/orchestrator/index.js:264:8)
  at /Users/ben/dev/test/node_modules/orchestrator/index.js:275:23
  at finish (/Users/ben/dev/test/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/ben/dev/test/node_modules/orchestrator/lib/runTask.js:29:3)
  at /Users/ben/dev/test/gulpfile.babel.js:390:9
  at removeAllListeners (/Users/ben/dev/test/node_modules/karma/lib/server.js:336:7)
  at Server.<anonymous> (/Users/ben/dev/test/node_modules/karma/lib/server.js:347:9)
  at Server.g (events.js:291:16)
  at emitNone (events.js:91:20)
  at Server.emit (events.js:185:7)
  at emitCloseNT (net.js:1558:8)
  at _combinedTickCallback (internal/process/next_tick.js:77:11)
  at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Same happens with new route generation.

**Comment by benmarten** [comment]
Can be fixed by adjusting the import

before:
```
'use strict';

describe('Component: TestComponent', function() {
  // load the controller's module
  beforeEach(module('test'));
```

after:
```
import test from './test.component';

describe('Component: TestComponent', function() {
  // load the controller's module
  beforeEach(angular.mock.module(test));
```

Let me know if that's right solution and I can send PR.

**Comment by Awk34** [comment]
LGTM

**Comment by benmarten** [comment]
I think this is part of the DaftMonk/generator-ng-component package...

**Comment by Awk34** [comment]
yep!
