### ISSUE TITLE
Upgraded angular version to 1.6.* in bower and now authentication error while logging-in in angular fullstack v2.1.1

### ISSUE THREAD

**Issue by akshayseth** [angular-fullstack/generator-angular-fullstack#2544]
I have recently installed angular fullstack v2.1.1 and have updated angular to 1.6.*.After bower install I am getting the error below:
UnauthorizedError: No authorization token was found
    at middleware (C:\Users\Ajax\Desktop\bookWorms\book-worm\node_modules\express-jwt\lib\index.js:80:21)
    at Middleware_Common_Object.<anonymous> (C:\Users\Ajax\Desktop\bookWorms\book-worm\server\auth\auth.service.js:24:7)
    at next (C:\Users\Ajax\Desktop\bookWorms\book-worm\node_modules\composable-middleware\lib\composable-middleware.js:59:18)

**Comment by Awk34** [comment]
The 2.x.x versions are no longer supported. Please take a look at the 3.x.x & 4.x.x versions

**Comment by akshayseth** [comment]
But I need angular 1 and when I install fullstack without specifying the version all I get is constructors and components.So I decided to go with fullstack v2.1.1

**Comment by Awk34** [comment]
4.1.1+ still uses Angular 1.6

**Comment by akshayseth** [comment]
Can you suggest me a reliable version of the generator which is compatible with angular 1.2.* ?

**Comment by Awk34** [comment]
I cannot. I don't even remember how long ago it was when we used Angular 1.2. Is there any reason you can't use 1.6?
