### ISSUE TITLE
TypeScript2.2

### ISSUE THREAD

**Issue by yoshiokatsuneo** [angular-fullstack/generator-angular-fullstack#2550]
- [*] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

I created a new TypeScript project, and updated to the latest TypeScript@2.2.0 by typing:
```
npm install typescript
```

But the, I got the error below on "gulp serve"

```
GET /api/things 200 11.038 ms - -
/private/tmp/yots3/node_modules/typescript/lib/typescript.js:3259
                throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
                ^

Error: Debug Failure. False expression: File  has unknown extension.
    at Object.assert (/private/tmp/yots3/node_modules/typescript/lib/typescript.js:3259:23)
    at Object.fail (/private/tmp/yots3/node_modules/typescript/lib/typescript.js:3264:19)
    at Object.extensionFromPath (/private/tmp/yots3/node_modules/typescript/lib/typescript.js:3406:15)
    at /private/tmp/yots3/node_modules/typescript/lib/typescript.js:63897:46
    at Array.map (native)
    at resolveModuleNamesWorker (/private/tmp/yots3/node_modules/typescript/lib/typescript.js:63891:141)
    at resolveModuleNamesReusingOldState (/private/tmp/yots3/node_modules/typescript/lib/typescript.js:64018:24)
    at processImportedModules (/private/tmp/yots3/node_modules/typescript/lib/typescript.js:64869:35)
    at findSourceFile (/private/tmp/yots3/node_modules/typescript/lib/typescript.js:64779:17)
    at processSourceFile (/private/tmp/yots3/node_modules/typescript/lib/typescript.js:64682:27)
```

How can I use the latest TypeScript 2.2 ?

Item | Version
----- | -----
generator-angular-fullstack | 4.2.0
Node | 6.10.2
npm | 3.10.10
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS |  SCSS 
Router |  ui-router
Client Tests | Mocha
DB | MongoDB
Auth | N

**Comment by Awk34** [comment]
You might need to update `awesome-typescript-loader` to a newer version as well. I haven't fully tested this, though.
