### ISSUE TITLE
Why does this come when I tipe in "gulp serve"?

### ISSUE THREAD

**Issue by lyct** [angular-fullstack/generator-angular-fullstack#2595]
Why does this come when I tipe in "gulp serve"?
Please help 

[19:01:08] Requiring external module babel-register
[19:01:14] Using gulpfile D:\ProxonityCP\gulpfile.babel.js
[19:01:14] Starting 'serve'...
[19:01:14] Starting 'clean:tmp'...
[19:01:14] Starting 'lint:scripts'...
[19:01:14] Starting 'lint:scripts:client'...
[19:01:14] Starting 'lint:scripts:server'...
[19:01:14] Starting 'inject'...
[19:01:14] Starting 'inject:less'...
[19:01:14] Starting 'copy:fonts:dev'...
[19:01:14] Starting 'env:all'...
[19:01:15] Finished 'env:all' after 35 ms
[19:01:15] Starting 'typings'...
[19:01:15] Finished 'clean:tmp' after 852 ms
[19:01:16] [gulp-tslint] error (eofline) polyfills.ts[32, 2]: file should end with a newline
[19:01:16] [gulp-tslint] error (no-trailing-whitespace) polyfills.ts[29, 1]: trailing whitespace
[19:01:16] [gulp-tslint] error (no-use-before-declare) polyfills.ts[21, 5]: variable 'ENV' used before declaration
[19:01:16] [gulp-tslint] error (whitespace) polyfills.ts[21, 3]: missing whitespace
[19:01:16] [gulp-tslint] error (whitespace) polyfills.ts[25, 3]: missing whitespace
[19:01:16] gulp-inject 4 files into app.less.
[19:01:16] Finished 'inject:less' after 2.04 s
[19:01:16] Finished 'inject' after 2.04 s
[19:01:17] [gulp-tslint] error (whitespace) app/app.ts[58, 11]: missing whitespace
[19:01:17] [gulp-tslint] error (class-name) components/auth/auth.service.ts[6, 7]: Class name must be in pascal case
[19:01:17] [gulp-tslint] error (whitespace) components/auth/auth.service.ts[28, 5]: missing whitespace
[19:01:18] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[7, 7]: missing whitespace
[19:01:18] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[11, 7]: missing whitespace
[19:01:18] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[13, 11]: missing whitespace
[19:01:18] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[25, 11]: missing whitespace
[19:01:19] Finished 'copy:fonts:dev' after 4.05 s
[19:01:19] Finished 'lint:scripts:server' after 4.21 s
[19:01:19] [gulp-tslint] error (whitespace) app/account/settings/settings.controller.ts[28, 7]: missing whitespace
[19:01:19] [gulp-tslint] error (whitespace) app/account/signup/signup.controller.ts[31, 7]: missing whitespace
[19:01:19] Finished 'lint:scripts:client' after 4.28 s
[19:01:19] Finished 'lint:scripts' after 4.28 s
[19:01:19] Finished 'typings' after 4.42 s
[19:01:19] Starting 'start:server'...
[19:01:19] Finished 'start:server' after 14 ms
[19:01:19] Starting 'start:client'...
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: D:\ProxonityCP\server/**/*
[nodemon] starting `node server`
module.js:457
    throw err;
    ^

Error: Cannot find module 'shrink-ray'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/ProxonityCP/server/config/express.js:10:1)
    at Module._compile (module.js:556:32)
    at loader (D:\ProxonityCP\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\ProxonityCP\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/ProxonityCP/server/app.js:29:1)
    at Module._compile (module.js:556:32)
    at loader (D:\ProxonityCP\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\ProxonityCP\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Awk34** [comment]
Please read the section in the [REAME](https://github.com/angular-fullstack/generator-angular-fullstack#usage) about installing dependencies for node-gyp, and the try re-installing shrink-ray

**Comment by bi-kai** [comment]
@Awk34  the same error to me:
```
Error: Cannot find module 'shrink-ray'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/node/www/test/test-angular-fullstack-1/server/config/express.js:10:1)
    at Module._compile (module.js:570:32)
    at loader (D:\node\www\test\test-angular-fullstack-1\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\node\www\test\test-angular-fullstack-1\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/node/www/test/test-angular-fullstack-1/server/app.js:29:1)
    at Module._compile (module.js:570:32)
    at loader (D:\node\www\test\test-angular-fullstack-1\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\node\www\test\test-angular-fullstack-1\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
[nodemon] app crashed - waiting for file changes before starting...
```
