### ISSUE TITLE
Comes error "iltorb@1.3.1 install: `node-pre-gyp install --fallback-to-build`" when npm install

### ISSUE THREAD

**Issue by bi-kai** [angular-fullstack/generator-angular-fullstack#2598]
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"a
ny"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\stylint\node_modules\chokidar\node_modul
es\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"a
ny"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node\\anzhuang\\node.exe" "D:\\node\\anzhuang\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.3.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\node\www\test\temp\npm-debug.log
```
what's wrong with it? Do i need to re-install local modules?

**Comment by bi-kai** [comment]
run `gulp serve`, show error bellow:
```
[15:55:33] [gulp-tslint] error (eofline) polyfills.ts[32, 2]: file should end with a newline
[15:55:33] [gulp-tslint] error (no-trailing-whitespace) polyfills.ts[29, 1]: trailing whitespace
[15:55:33] [gulp-tslint] error (no-use-before-declare) polyfills.ts[21, 5]: variable 'ENV' used before declaration
[15:55:33] [gulp-tslint] error (whitespace) polyfills.ts[21, 3]: missing whitespace
[15:55:33] [gulp-tslint] error (whitespace) polyfills.ts[25, 3]: missing whitespace
[15:55:35] gulp-inject 5 files into app.scss.
[15:55:36] Finished 'inject:scss' after 6.14 s
[15:55:36] Finished 'inject' after 6.15 s
[15:55:36] [gulp-tslint] error (whitespace) app/app.ts[58, 11]: missing whitespace
[15:55:38] [gulp-tslint] error (class-name) components/auth/auth.service.ts[6, 7]: Class name must be in pascal case
[15:55:38] [gulp-tslint] error (whitespace) components/auth/auth.service.ts[28, 5]: missing whitespace
[15:55:38] Finished 'copy:fonts:dev' after 8.01 s
[15:55:38] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[7, 7]: missing whitespace
[15:55:38] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[11, 7]: missing whitespace
[15:55:38] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[13, 11]: missing whitespace
[15:55:38] [gulp-tslint] error (whitespace) components/auth/router.decorator.ts[25, 11]: missing whitespace
[15:55:40] [gulp-tslint] error (whitespace) app/account/settings/settings.controller.ts[28, 7]: missing whitespace
[15:55:40] Finished 'lint:scripts:server' after 10 s
[15:55:40] [gulp-tslint] error (whitespace) app/account/signup/signup.controller.ts[31, 7]: missing whitespace
[15:55:40] Finished 'lint:scripts:client' after 11 s
```

```
[nodemon] starting `node server`
module.js:471
    throw err;
    ^

Error: Cannot find module 'shrink-ray'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/node/www/test/test-angular-fullstack/server/config/express.js:10:1)
    at Module._compile (module.js:570:32)
    at loader (D:\node\www\test\test-angular-fullstack\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\node\www\test\test-angular-fullstack\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:/node/www/test/test-angular-fullstack/server/app.js:29:1)
    at Module._compile (module.js:570:32)
    at loader (D:\node\www\test\test-angular-fullstack\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\node\www\test\test-angular-fullstack\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by DanMMX** [comment]
you can check #2441 and #2309 for possible workarounds

**Comment by bi-kai** [comment]
do not help, just close the issue.
