### ISSUE TITLE
cannot install shrink-ray module

### ISSUE THREAD

**Issue by bi-kai** [angular-fullstack/generator-angular-fullstack#2599]
when i install shrink-ray locally with `npm i shrink-ray`, it comes error:
```
PS D:\node\www\test\temp> npm i shrink-ray

> iltorb@1.3.1 install D:\node\www\node_modules\iltorb
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://node-iltorb.s3.amazonaws.com/iltorb/v1.3.1/node-v48-win32-x64.
tar.gz
node-pre-gyp ERR! Pre-built binaries not found for iltorb@1.3.1 and node@6.10.3 (node-v48 ABI) (falling back to source
 compile with node-gyp)
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: tunneling socket could not be established, statusCode=407
gyp ERR! stack     at ClientRequest.onConnect (D:\node\www\node_modules\tunnel-agent\index.js:165:19)
gyp ERR! stack     at ClientRequest.g (events.js:292:16)
gyp ERR! stack     at emitThree (events.js:116:13)
gyp ERR! stack     at ClientRequest.emit (events.js:194:7)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:394:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:176:18)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:134:10)
gyp ERR! stack     at TCP.onread (net.js:547:20)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\node\\anzhuang\\node.exe" "D:\\node\\www\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
"--fallback-to-build" "--module=D:\\node\\www\\node_modules\\iltorb\\build\\bindings\\encode.node" "--module_name=enco
de" "--module_path=D:\\node\\www\\node_modules\\iltorb\\build\\bindings"
gyp ERR! cwd D:\node\www\node_modules\iltorb
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\node\anzhuang\node.exe D:\node\www\node_modules\node-gyp\bin\node
-gyp.js configure --fallback-to-build --module=D:\node\www\node_modules\iltorb\build\bindings\encode.node --module_nam
e=encode --module_path=D:\node\www\node_modules\iltorb\build\bindings' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\node\www\node_modules\iltorb\node_modules\node-pre-gyp\lib
\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "D:\\node\\anzhuang\\node.exe" "D:\\node\\www\\node_modules\\iltorb\\node_modules\\node-pre-
gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\node\www\node_modules\iltorb
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute 'D:\node\anzhuang\node.exe D:\node\www\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to
-build --module=D:\node\www\node_modules\iltorb\build\bindings\encode.node --module_name=encode --module_path=D:\node\
www\node_modules\iltorb\build\bindings' (1)
angular-proj@1.0.0 D:\node\www
+-- bytes@2.2.0  extraneous
+-- compressible@2.0.10  extraneous
+-- node-zopfli@1.4.0  extraneous
+-- on-headers@1.0.1  extraneous
`-- stream-buffers@3.0.1  extraneous

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"a
ny"} (current: {"os":"win32","arch":"x64"})
npm WARN angular-proj@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node\\anzhuang\\node.exe" "D:\\node\\anzhuang\\node_modules\\npm\\bin\\npm-cli.js" "i" "shrink-ray"

npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! iltorb@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iltorb@1.3.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iltorb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iltorb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iltorb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\node\www\test\temp\npm-debug.log
```
the error is `Tried to download(undefined): https://node-iltorb.s3.amazonaws.com/iltorb/v1.3.1/node-v48-win32-x64.tar.gz`, I can download the package in browser, but it cannot be accessed by cmd. 
what can i do then? 
**Does node-gyp have proxy**?

**Comment by DanMMX** [comment]
you can check #2441 and #2309 for possible workarounds

**Comment by bi-kai** [comment]
do not helpful, just close the issue.
