### ISSUE TITLE
3.x on node 6.5 not working?

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#2638]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 6.5.0
npm | 3.10.3
Operating System Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | LESS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y

Hi there 

Does version 3.x not work with node 6.x?

The terminal throuws this error on my linux machine, but on windows where I have still node -v 3.x running it works as a charm.

```
/media/marinus/Data/web/svs/node_modules/jshint/src/jshint.js:5309
        throw err;
        ^

TypeError: Cannot read property 'type' of null
  at checkPunctuators (/media/marinus/Data/web/svs/node_modules/jshint/src/jshint.js:4834:14)
  at Object.fud (/media/marinus/Data/web/svs/node_modules/jshint/src/jshint.js:4201:11)
  at expression (/media/marinus/Data/web/svs/node_modules/jshint/src/jshint.js:881:32)
  at statement (/media/marinus/Data/web/svs/node_modules/jshint/src/jshint.js:1632:9)
  at statements (/media/marinus/Data/web/svs/node_modules/jshint/src/jshint.js:1677:16)
  at itself (/media/marinus/Data/web/svs/node_modules/jshint/src/jshint.js:5288:9)
  at /media/marinus/Data/web/svs/node_modules/gulp-jshint/src/lint.js:93:21
  at respond (/media/marinus/Data/web/svs/node_modules/rcloader/index.js:78:7)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)


```

Kind Regards

Marinus

**Comment by Awk34** [comment]
Node didn't have a 3.x.x version. Do you mean 4.x.x?

Anyhow, I believe the generator 4.x.x version came out before node 6.x.x became LTS, thus testing was done on it and not 3.x.x
