### ISSUE TITLE
gulp serve not working after nodejs update

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#2689]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 9.5.0
npm | 5.6.0
Operating System Windows 10

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | LESS
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y

Hi there 
After updating to the latest nodejs version gulp serve throws the following error:
`module.js:557
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:660:30)
    at Module._extensions..js (module.js:671:10)
    at Object.require.extensions.(anonymous function) [as .js] (m:\Websites\projekte\Kunden\SVS\svs-ngFullStack\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:573:32)`

I have updated all npm and bower packages.

What should I do?

**Comment by Awk34** [comment]
Have you done any research into the issue?

My first guess would be to wipe and re-install your global npm packages.

**Comment by Awk34** [comment]
I'm guessing this isn't a generator issue

**Comment by kathy-ems** [comment]
This happened to me too. I'm now using node v9.6.1.

**Comment by MarinAngelo** [comment]
oke, I vent back to node 5.6.0, so it works, thanks!

**Comment by kathy-ems** [comment]
I'll continue to work at getting the newest version of Node to work with this generator because I want to use async/await without `--harmony` flag.

**Comment by kathy-ems** [comment]
This article resolved my issue: https://stackoverflow.com/questions/25090452/gulp-command-not-found-after-install

Run the following:
`npm config set prefix /usr/local`
`sudo npm install gulp -g`

In addition, I had to remove the api auth and user from the generator code.
Lines 20-23 from 'server/app.js'
Lines 13 and 17 from 'server/routes.js'
