### ISSUE TITLE
angular-fullstack:route generator throws error

### ISSUE THREAD

**Issue by gintsgints** [angular-fullstack/generator-angular-fullstack#2701]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-rc.1
Node | v8.10.0
npm | 5.7.1
Operating System | Windows 10 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | SCSS
Router | ui-router
Client Tests | Jasmine
DB | MongoDB
Auth | Y

After I try generate route,

```
yo angular-fullstack:route users
```

 I get error:
var Generator = yeoman.Base.extend({
                            ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (C:\Users\gpolis\AppData\Roaming\npm\node_modules\generator-angular-fullstack\generators\route\index.js:5:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.get [as angular-fullstack:route] (C:\Users\gpolis\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
    at Store.get (C:\Users\gpolis\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)

**Comment by Awk34** [comment]
Sorry, the subgenerators are not supported for the 5.0.0 RC yet

**Comment by bodagetta** [comment]
How do I install an older version that still supports generators? 

`npm i -g generator-angular-fullstack`

installs the beta and I'd really like to have a more stable platform that includes generators.

**Comment by Awk34** [comment]
The latest AngularJS 1.x supporting version is `4.2.2`, so `npm i -g generator-angular-fullstack@4.2.2`

**Comment by albert-92** [comment]
Wasn't the latest stable `4.2.3`?

**Comment by Awk34** [comment]
this has been added in 5.0.0-rc.2
