### ISSUE TITLE
Error: Cannot find module 'shrink-ray'

### ISSUE THREAD

**Issue by Jaouad-am** [angular-fullstack/generator-angular-fullstack#2723]
`[nodemon] starting `node server`
module.js:549
    throw err;
    ^

Error: Cannot find module 'shrink-ray'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:/Projects/meanstore/server/config/express.js:10:1)
    at Module._compile (module.js:652:30)
    at loader (D:\Projects\meanstore\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Projects\meanstore\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:/Projects/meanstore/server/app.js:29:1)
    at Module._compile (module.js:652:30)
    at loader (D:\Projects\meanstore\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Projects\meanstore\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
[nodemon] app crashed - waiting for file changes before starting...`

Item | Version
----- | -----
generator-angular-fullstack | 4.2.2
Node | v8.11.2
npm | 6.1.0
Operating System |  Windows 10 
Python | 27
windows-build-tools | 3.0.0
gulp | 3.9.0
gulp-cli | 2.0.1
node-gyp | 3.6.2
node-pre-gyp | 0.10.0
express | 4.16.3
babel-core | 6.26.3
babel-register | 6.26.0

Item | Answer
----- | -----
Transpiler | Babel with flowtype
Markup | HTML 
CSS | SASS
Router |  ui-router
Client Tests |  Mocha
DB | MongoDB 
Auth | Y 
etc | etc
i searched and tried everything on the web nothing seems to work ... im not sure if its from the generator or the global packages im using the generator for angularjs if you need more infos plz ask me thanks.

**Comment by Awk34** [comment]
If you search through our issues you'll see that you aren't the only one who has had this issue. 4.2.3 specifically removed this dependency. See this commit on what to change: https://github.com/angular-fullstack/generator-angular-fullstack/commit/e225a67534b007c369b5cf474444c045d2aa0b1d
