### ISSUE TITLE
With a newly generated project, gulp serve fails with: ImportDeclaration should appear when the mode is ES6 and in the module context.

### ISSUE THREAD

**Issue by jspenc72** [angular-fullstack/generator-angular-fullstack#2746]
- [x ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 5.0.0-rc.3 
Node | v10.6.0
npm | 6.1.0
Operating System | OS X 10

Item | Answer
----- | -----
Transpiler | Babel / TypeScript (Tried generating project with either Babel or Typescript, same error.)
Markup | HTML 
CSS | SCSS
Router | ui-router
Client Tests | Mocha
DB | MongoDB / SQL (Both, MongoDB is default)
Auth | Y

```bash
$ gulp serve
[18:46:24] Failed to load external module @babel/register
[18:46:24] Requiring external module babel-register
[18:46:26] Using gulpfile ~/dev/dryfti-api-core/gulpfile.babel.js
[18:46:26] Starting 'serve'...
[18:46:26] Starting 'clean:tmp'...
[18:46:26] Starting 'lint:scripts'...
[18:46:26] Starting 'lint:scripts:client'...
[18:46:26] Starting 'lint:scripts:server'...
[18:46:26] Starting 'inject'...
[18:46:26] Starting 'inject:scss'...
[18:46:26] Starting 'copy:fonts:dev'...
[18:46:26] Starting 'env:all'...
[18:46:26] Finished 'env:all' after 3.71 ms
[18:46:26] Finished 'clean:tmp' after 50 ms
assert.js:269
    throw err;
    ^

AssertionError [ERR_ASSERTION]: ImportDeclaration should appear when the mode is ES6 and in the module context.
  at Referencer.ImportDeclaration (/Users/jessespencer/dev/dryfti-api-core/node_modules/escope/lib/referencer.js:591:34)
  at Referencer.Visitor.visit (/Users/jessespencer/dev/dryfti-api-core/node_modules/esrecurse/esrecurse.js:104:34)
  at Referencer.Visitor.visitChildren (/Users/jessespencer/dev/dryfti-api-core/node_modules/esrecurse/esrecurse.js:83:38)
  at Referencer.Program (/Users/jessespencer/dev/dryfti-api-core/node_modules/escope/lib/referencer.js:419:18)
  at Referencer.Visitor.visit (/Users/jessespencer/dev/dryfti-api-core/node_modules/esrecurse/esrecurse.js:104:34)
  at Object.analyze (/Users/jessespencer/dev/dryfti-api-core/node_modules/escope/lib/index.js:153:16)
  at EventEmitter.module.exports.api.verify (/Users/jessespencer/dev/dryfti-api-core/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:850:35)
  at processText (/Users/jessespencer/dev/dryfti-api-core/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:263:31)
  at CLIEngine.executeOnText (/Users/jessespencer/dev/dryfti-api-core/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:761:26)
  at verify (/Users/jessespencer/dev/dryfti-api-core/node_modules/gulp-eslint/index.js:20:23)
  at Transform._transform (/Users/jessespencer/dev/dryfti-api-core/node_modules/gulp-eslint/index.js:68:18)
  at Transform._read (_stream_transform.js:190:10)
  at Transform._write (_stream_transform.js:178:12)
  at doWrite (_stream_writable.js:410:12)
  at writeOrBuffer (_stream_writable.js:394:5)
  at Transform.Writable.write (_stream_writable.js:294:11)
  at Stream.method [as write] (/Users/jessespencer/dev/dryfti-api-core/node_modules/duplexer/index.js:47:39)
  at write (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:182:13)
  at emitReadable_ (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:182:13)
  at emitReadable_ (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /Users/jessespencer/dev/dryfti-api-core/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by kkrb** [comment]
@jspenc72 I faced the same **'AssertionError [ERR_ASSERTION]: I .....'** and it got resolved by upgrading 'gulp-eslint' to version '^5.0.0' in the '**package.json**'. Additionally, i had to follow the instructions provided [here](https://github.com/angular-fullstack/generator-angular-fullstack/issues/2697) to get the default app up and running via **'gulp serve'** command

**Comment by Awk34** [comment]
Yes, please read the documentation, as `gulp serve` is no longer the recommended way of starting up the app.

**Comment by jspenc72** [comment]
@kkrb thanks for the response!
