### ISSUE TITLE
Request Error : Error in plugin 'run-sequence(spsync:sync)'

### ISSUE THREAD

**Issue by PrabhaSP2010** [angular-fullstack/generator-angular-fullstack#2762]
Hi,
I am getting an below error while executing the "gulp spsync" command from command prompt

[15:16:12] 'spsync:sync' errored after 273 ms
[15:16:12] Error in plugin 'gulp-spsync'
Message:
    Request error
[15:16:12] Error in plugin 'run-sequence(spsync:sync)'
Error
    at finish (C:\mainfolder\subfolder\subfolder\node_modules\run-sequence\index.js:56:13)
    at Gulp.onError (C:\mainfolder\subfolder\subfolder\node_modules\run-sequence\index.js:67:4)
    at emitOne (events.js:121:20)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (C:\mainfolder\subfolder\subfolder\node_modules\orchestrator\index.js:264:8)
    at C:\mainfolder\subfolder\subfolder\node_modules\orchestrator\index.js:275:23
    at finish (C:\mainfolder\subfolder\subfolder\node_modules\orchestrator\lib\runTask.js:21:8)
    at DestroyableTransform.<anonymous> (C:\mainfolder\subfolder\subfolder\node_modules\orchestrator\lib\runTask.js:52:4)
    at DestroyableTransform.f (C:\mainfolder\subfolder\subfolder\node_modules\once\once.js:17:25)
    at emitOne (events.js:121:20)
    at DestroyableTransform.emit (events.js:211:7)
    at onwriteError (C:\mainfolder\subfolder\subfolder\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:449:12)
    at onwrite (C:\mainfolder\subfolder\subfolder\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:470:11)
    at WritableState.onwrite (C:\mainfolder\subfolder\subfolder\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform (C:\mainfolder\subfolder\subfolder\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:93:3)
    at C:\mainfolder\subfolder\subfolder\node_modules\gulp-spsync\index.js:471:5
    at tryCatcher (C:\mainfolder\subfolder\subfolder\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\mainfolder\subfolder\subfolder\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\mainfolder\subfolder\subfolder\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\mainfolder\subfolder\subfolder\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\mainfolder\subfolder\subfolder\node_modules\bluebird\js\release\promise.js:690:18)
    at _drainQueueStep (C:\mainfolder\subfolder\subfolder\node_modules\bluebird\js\release\async.js:138:12)

Can any one please help me on this issue. And build is working without any issue.

**Comment by Awk34** [comment]
We have no such Gulp task named "spsync"

**Comment by PrabhaSP2010** [comment]
Can you please provide me any best worked example to copy the files from local to SharePoint by using gulp-spsync
