### ISSUE TITLE
Not able to signup or log in

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#2776]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 10.3.0
npm | 6.1.0
Operating System Ubuntu 16.04

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | Styus
Router | ui-router
Client Tests | Mocha
DB | MongoDB
Auth | Y

I am not able to signup or login anymore. When singning up I have the following errors:
in the terminal:
`crypto.js:694
    throw new TypeError(
    ^

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:694:11)
    at Object.exports.pbkdf2 (crypto.js:682:10)
    at model.encryptPassword (/home/marinangelo/web/ubsfit/server/api/user/user.model.js:221:19)
    at /home/marinangelo/web/ubsfit/server/api/user/user.model.js:120:12
    at RandomBytes.ondone (/home/marinangelo/web/ubsfit/server/api/user/user.model.js:190:9)
Stopping Express server`

in the browser console: 
`POST http://localhost:9000/api/users net::ERR_CONNECTION_REFUSED`

and

`angular.js:14199 TypeError: Cannot read property 'errors' of null
    at signup.controller.js:40
    at processQueue (angular.js:16696)
    at angular.js:16712
    at Scope.$eval (angular.js:17994)
    at Scope.$digest (angular.js:17808)
    at Scope.$apply (angular.js:18102)
    at done (angular.js:12082)
    at completeRequest (angular.js:12291)
    at XMLHttpRequest.requestError (angular.js:12229)`

Any idea?

**Comment by MarinAngelo** [comment]
no support anymore for old version?

**Comment by albert-92** [comment]
If it worked before, then either your node.js version is too new (try to downgrade), or you installed some new package version which in incompatible, or you changed something in your code.

Why don't you check the codelines from the stacktrace and try to find out what is going on?

This generator is already at version 5, so nobody knows what is going on in your code.
Oh and by the way, it is open source, so actually there is no support at all, just help from other people.

> I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.
