### ISSUE TITLE
Cannot find module 'callsites'

### ISSUE THREAD

**Issue by xiandalisay** [angular-fullstack/generator-angular-fullstack#2781]
generator-angular-fullstack 4.2.0 
Node 10.15.3
npm 6.4.1
Operating System Windows 10 Pro

Error Details

yo angular-fullstack

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'callsites'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\DevP\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\caller-path\index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\DevP\AppData\Roaming\npm\node_modules\generator-angular-fullstack\node_modules\require-uncached\index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by thierryskoda** [comment]
@xiandalisay Hi, I have the same error. Have you ever found what's causing this? Thank you very much

**Comment by xiandalisay** [comment]
@thierryskoda The error is a dependency issue of this module.
