### ISSUE TITLE
app generator fails: `Object #<Environment> has no method 'instantiate' `

### ISSUE THREAD

**Issue by foxyblocks** [angular-fullstack/generator-angular-fullstack#308]
Running `yo angular-fullstack [app-name]` fails with:

```
/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:551
    generator = this.env.instantiate(Generator, options);
                         ^
TypeError: Object #<Environment> has no method 'instantiate'
    at composeWith (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:551:26)
    at yeoman.generators.Base.extend.compose (/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js:194:10)
    at /usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:387:14
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

**Comment by np0x** [comment]
make sure you also have all yeoman installed correctly, you will see similar errors if you don't have bower, grunt-cli and gulp installed.  

http://yeoman.io/learning/index.html
