### ISSUE TITLE
generator-angular-fullstack error

### ISSUE THREAD

**Issue by corporationsruleyourmom** [angular-fullstack/generator-angular-fullstack#334]
Hello, and thanks for this great generator! I've used previous versions 1.x without problems but ever since I upgraded to yeoman 1.x and generator-angular-fullstack to 2.x I've been unsuccessful in generating some working boilerplate. Ideally I'd like to generate a project that works using Openshift for deployment. I'm using `node -v v.0.10.29`, `npm -v 1.4.14`, on Ubuntu server 12.04. Would creating the .yo-rc.json file help fix this issue?

The error I'm receiving when running `yo angular-fullstack` is this:

```
fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/home/my-user-name/fullstack-demo/.yo-rc.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at Storage.forceSave (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/util/storage.js:63:6)
    at yeoman.generators.Base.extend.saveSettings (/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js:175:17)
    at /usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:387:14
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

I've also tried to run the generator passing openshift `yo angular-fullstack:openshift` and I get this error:

```
Initializing deployment repo

/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/mkdirp/index.js:89
                    throw err0;
                          ^
Error: EACCES, permission denied '/home/my-user-name/fullstack-demo/dist'
    at Object.fs.mkdirSync (fs.js:647:18)
    at Function.sync (/usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/node_modules/mkdirp/index.js:70:13)
    at Generator.gitInit (/usr/local/lib/node_modules/generator-angular-fullstack/openshift/index.js:57:8)
    at /usr/local/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:387:14
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

Any help would be greatly appreciated. Once again, thanks for all your contributions and help!

**Comment by dagi377** [comment]
Go  a head and create the directory you want the app on manually with out sudo command,I have done that and it worked for me. It is all about permission. Or try with sudo command if you are on ubuntu
