### ISSUE TITLE
e-mail confirmation at register & forgotten password

### ISSUE THREAD

**Issue by nschurmann** [angular-fullstack/generator-angular-fullstack#462]
Sup guys, is there a configuration to make the registration process to validate the email first? The use case is basically so the users don't start registering emails that are not of their property, this could lead to users impersonating other persons.

**Comment by kingcody** [comment]
@remicastaing, I've taken a good bit from your idea of the underlying mailer functionality and attempted to implement it as a standalone feature. I already have some additional code that builds upon this mailer framework to send out email verification emails. Take a look and let me know what you think:
https://github.com/kingcody/generator-angular-fullstack/tree/feature/mail-support

Maybe we can get something like this tested and worked out and continue implementing the email verification on top of it...

/cc @jeffbuhrt @JaKXz

**Comment by remicastaing** [comment]
First thoughts:
- great that you added all this optional support for all transport!
- wouldn't it be better to ask for scaffolding out a mailer boilerplate after and only if there is an authentication boilerplate? Or it is just for generating admin email alert?

I was exited to see your work and now I'm frustrated: 

```
> node-sass@1.2.3 install /Users/remi/Workspaces/JS/mail-support/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/remi/Workspaces/JS/mail-support/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/remi/Workspaces/JS/mail-support/node_modules/node-sass
> node scripts/build.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'escape-string-regexp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/remi/Workspaces/JS/mail-support/node_modules/mocha/lib/mocha.js:12:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/remi/.nvm/v0.10.32/bin/node" "/Users/remi/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /Users/remi/Workspaces/JS/mail-support
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by kingcody** [comment]
@remicastaing
> wouldn't it be better to ask for scaffolding out a mailer boilerplate after and only if there is an authentication boilerplate? Or it is just for generating admin email alert?

Well my thought for this was that its a nice basic mailer layout that can be used for lots of different purposes. That being said, I think that the email verification prompt could be when `answers.email && answers.auth`

On the note of `node-sass` failing to install, I'm terribly sure about that. It definitely installs fine on my Linux machine running node `v0.10.32`

**Comment by remicastaing** [comment]
I've done nothing except sleeping and running over the yo generator in a new folder and now it works. Weird!

**Comment by kingcody** [comment]
Here is a WIP that uses the mailer feature to add email verification and password recovery to the generator.

https://github.com/kingcody/generator-angular-fullstack/tree/temp/account-emails

It currently lacks client side pages to facilitate the api usage. However I figured that posting it here might get some feedback or give someone else some ideas.

**Comment by remicastaing** [comment]
@kingcody, your mailer works fine for me and I'm happy with what you have done.

Have you ever tried to use `@import` in your .scss files? I couldn't use it without crashing.

**Comment by b4dtR1p** [comment]
you have any updates on this topic?

**Comment by canercak** [comment]
@remicastaing thank you for your work, I just changed the ejs templates such as;
<p class="lead">Kick-start your next web app with <%= COMPANY %> </p>
the rest perfectly integrates into generated app

**Comment by bryangrimes** [comment]
I see this was marked for 3.2.0 but I can't see anything else on this feature, did this in fact get rolled into that release and I'm somehow missing it?

**Comment by Tings** [comment]
@remicastaing You are awesome! Thank you :+1:
