### ISSUE TITLE
Cannot install: npm ERR! Error: shasum check failed

### ISSUE THREAD

**Issue by jonniedarko** [angular-fullstack/generator-angular-fullstack#49]
I get the following error when I run the install command:

```
npm install -g generator-angular-fullstack
npm http GET https://registry.npmjs.org/generator-angular-fullstack
npm http 304 https://registry.npmjs.org/generator-angular-fullstack
npm http GET https://registry.npmjs.org/generator-angular-fullstack/-/generator-angular-fullstack-1.2.0.tgz
npm http 200 https://registry.npmjs.org/generator-angular-fullstack/-/generator-angular-fullstack-1.2.0.tgz
npm ERR! Error: shasum check failed for /var/folders/zv/32jxd3d96x77qnd_wrhhg6q00000gn/T/npm-55977-irCte8hl/1389531052087-0.5481911019887775/tmp.tgz
npm ERR! Expected: 64c3cae6c4821887ccf5361d3bdacf14ab43606d
npm ERR! Actual:   d3cba4b72f16fe3b7a61839f484c4367c53ee487
npm ERR!     at /usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/Cellar/node/0.10.24/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.24/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-angular-fullstack"
npm ERR! cwd /Users/user1/code/mean/yo-mean
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/user1/code/mean/yo-mean/npm-debug.log
npm ERR! not ok code 0

```

**Comment by Sofia-H** [comment]
I got the same error. 
node v0.10.24 
npm 1.3.21
I tried to reinstall and it worked now.thanks @DaftMonk

**Comment by yangfan0095** [comment]
i got the same error  to

**Comment by yangfan0095** [comment]
应该是网络问题吧

**Comment by codegreenie** [comment]
I pray that truly, it is a network issue. Hopefully will work by midnight.
